#!/usr/bin/env bash
# ═════════════════════════════════════════════════════════════════════════════
# scripts/db/bundle.sh FROM TO — concatenate the numbered migrations FROM..TO (inclusive)
# into ONE paste-able file for the Supabase SQL editor (blueprint §7.1 "bundle script").
#
#   scripts/db/bundle.sh 1 6     → supabase/bundles/01-06.sql  (01_… through 06_…)
#   scripts/db/bundle.sh 30 34   → supabase/bundles/30-34.sql  (the demo seeds)
#
# The numbered files in supabase/migrations/ remain the SOURCE OF TRUTH; a bundle is a
# disposable convenience. Every file is idempotent, so re-pasting a bundle is safe.
# Refuses to bundle a file that contains psql meta-commands (lines starting with "\"),
# because the SQL editor cannot run them.
# ═════════════════════════════════════════════════════════════════════════════
set -Eeuo pipefail
export LANG=C LC_ALL=C

usage() { echo "usage: $0 FROM TO   (migration numbers, e.g. 1 6 or 01 06)" >&2; exit 2; }
[[ $# -eq 2 ]] || usage
[[ "$1" =~ ^[0-9]{1,3}$ && "$2" =~ ^[0-9]{1,3}$ ]] || usage
FROM=$((10#$1))
TO=$((10#$2))
(( FROM <= TO )) || { echo "bundle.sh: FROM ($FROM) must be <= TO ($TO)" >&2; exit 2; }

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
MIG_DIR="$ROOT/supabase/migrations"
OUT_DIR="$ROOT/supabase/bundles"
OUT="$OUT_DIR/$(printf '%02d' "$FROM")-$(printf '%02d' "$TO").sql"

shopt -s nullglob
selected=()
for f in "$MIG_DIR"/*.sql; do
  base="$(basename "$f")"
  num="${base%%_*}"
  [[ "$num" =~ ^[0-9]+$ ]] || continue
  n=$((10#$num))
  if (( n >= FROM && n <= TO )); then selected+=("$f"); fi
done
shopt -u nullglob

[[ ${#selected[@]} -gt 0 ]] || { echo "bundle.sh: no migrations numbered $FROM..$TO in $MIG_DIR" >&2; exit 1; }

for f in "${selected[@]}"; do
  if grep -nE '^[[:space:]]*\\' "$f" >/dev/null; then
    echo "bundle.sh: $(basename "$f") contains psql meta-commands (lines starting with '\\'); the SQL editor cannot run them" >&2
    exit 1
  fi
done

mkdir -p "$OUT_DIR"
tmp="$(mktemp "${TMPDIR:-/tmp}/dockone-bundle.XXXXXX")"
trap 'rm -f "$tmp"' EXIT
{
  echo "-- ═════════════════════════════════════════════════════════════════════════════"
  echo "-- Dock One Solutions — migration bundle $(printf '%02d' "$FROM")..$(printf '%02d' "$TO")"
  echo "-- Generated by scripts/db/bundle.sh on $(date -u '+%Y-%m-%d %H:%M UTC'). DO NOT EDIT THIS FILE:"
  echo "-- the numbered files in supabase/migrations/ are the source of truth. Every file is"
  echo "-- idempotent, so pasting this bundle again is safe. Contents, in order:"
  for f in "${selected[@]}"; do echo "--   $(basename "$f")"; done
  echo "-- Read each file's OPS NOTE (at its end): some features stay off until you act."
  echo "-- ═════════════════════════════════════════════════════════════════════════════"
  for f in "${selected[@]}"; do
    base="$(basename "$f")"
    echo
    echo
    echo "-- ┌───────────────────────────────────────────────────────────────────────────"
    echo "-- │ BEGIN $base"
    echo "-- └───────────────────────────────────────────────────────────────────────────"
    cat "$f"
    # guarantee a newline between files so the last statement of one never fuses with the next
    [[ -z "$(tail -c1 "$f")" ]] || echo
    echo "-- ── END $base ─────────────────────────────────────────────────────────────"
  done
} >"$tmp"
chmod 644 "$tmp"
mv "$tmp" "$OUT"
trap - EXIT
echo "wrote $OUT (${#selected[@]} file(s): $(for f in "${selected[@]}"; do basename "$f" .sql; done | paste -sd ' ' -))"
