#!/usr/bin/env python3
"""
Builds supabase/migrations/36_seed_inventory_update.sql from the client's second stock list
(Categorized_Product_Stock.xlsx, sheet "Products"), applied ON TOP of 34_seed_inventory (already
live). What the second list adds or corrects — every quantity is read from its cell:

  · new product   ASUS VivoBook E1504FA-BQ2909 (1 in stock; brand match from the first workbook)
  · new variant   JBL Tune 730BT — White (1 in stock)
  · stock         A1504VA-BQ541, Logitech MK270, Cruzer Blade 16GB — the stock list's count wins
                  (approved), written only while the stock still holds 34's figure
  · details       Blackshadow keyboards are Black; of the 3 One Touch 2TB, 2 are stated Black →
                  that variant is "2TB" (was "2TB Black"); "gaming laptop" tag from the sheet's
                  product type
No prices are supplied by this list, so the two new items arrive switched off until priced.
Ignored: the list's mis-filings (4-in-1 combo packs filed as "Glide Mousepad", instax mini 12 as
"Instant film") and rows that only regroup the same stock.

Run:  python3 scripts/db/inventory/build_update.py "~/Downloads/Categorized_Product_Stock (1).xlsx" \
                                                   ~/Downloads/Dock_One_Combined_Inventory.xlsx
"""

import sys
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "supabase/migrations/36_seed_inventory_update.sql"
SHEET2 = "Categorized_Product_Stock.xlsx"


def q(value):
    if value is None:
        return "NULL"
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def read(path2, path1):
    rows = {}
    for i, r in enumerate(openpyxl.load_workbook(path2, data_only=True)["Products"].iter_rows(min_row=6, values_only=True), start=6):
        if any(v is not None for v in r):
            rows[r[12]] = dict(row=i, category=r[0], type=r[1], brand=r[2], model=r[3], variation=r[4], qty=r[10], source_row=r[13])
    brand = {}
    for r in openpyxl.load_workbook(path1, data_only=True)["Brand Content"].iter_rows(min_row=6, values_only=True):
        if r[0]:
            brand[r[0]] = dict(title=r[1], wording=r[3], url=r[4], notes=r[5])
    return rows, brand


def get(rows, text):
    assert text in rows, f"stock list has no row '{text}'"
    return rows[text]


def build(rows, brand):
    e1504 = get(rows, "ASUS VIVOBOOK E1504FA-BQ2909")
    t730w = get(rows, "JBL OVER HEADPHONE T730 BT - WHITE")
    a1504 = get(rows, 'ASUS VivoBook A1504VA-BQ541 Core 5 120U 8GB DDR5 512GB SSD 15.6" FHD')
    mk270 = get(rows, "Logitech Keyboard Wireless MK270 920-004519")
    blade16 = get(rows, "SanDisk 16GB Flash Cruzer Blade CZ50")
    ot2 = get(rows, "Seagate 2TB One Touch External Hard Disk")
    ot2b = get(rows, 'Seagate 2TB External HDD One Touch 2.5" Black')
    bs = [get(rows, "Keyboard Blackshadow (Blue Switch)"), get(rows, "Keyboard Blackshadow (Red Switch)")]
    assert all("Black" in r["variation"] for r in bs)
    gaming = sorted({r["model"] for r in rows.values() if r["type"] == "Gaming laptop"})
    assert gaming == ["Cyborg 15", "Cyborg 15 Gaming", "LOQ 15AHP9", "TUF A18 FA808UH-RS74"], gaming
    b = brand["E1504FA"]
    e1504_notes = b["notes"] + " Not in the first workbook's stock rows and no price supplied: set a price, then switch the variant on."

    # (slug, variant, new qty, 34's qty, sheet row)
    stock = [("asus-vivobook-a1504va-bq541", "Standard", a1504["qty"], 1, a1504["row"]),
             ("logitech-mk270-wireless-keyboard-mouse-combo", "Standard", mk270["qty"], 2, mk270["row"]),
             ("sandisk-cruzer-blade-cz50", "16GB", blade16["qty"], 0, blade16["row"])]
    ot_total = ot2["qty"] + ot2b["qty"]
    new_units = e1504["qty"] + t730w["qty"]
    stock_vals = ",\n".join(f"      ({q(s)}, {q(v)}, {n}, {old}, {row})" for s, v, n, old, row in stock)

    return f"""-- ═════════════════════════════════════════════════════════════════════════════
-- {OUT.name} — Dock One Solutions
-- GENERATED by scripts/db/inventory/build_update.py from the client's second stock list
-- ({SHEET2}). Do not hand-edit — change the script and re-run it.
--
-- PURPOSE      Applies what the second stock list adds to the catalogue 34 created (34 is live,
--              so this is a separate step). No prices in this list: new items arrive OFF.
--                · NEW product  ASUS VivoBook E1504FA-BQ2909 — {e1504['qty']} in stock, no price (switched off)
--                · NEW variant  JBL Tune 730BT — White, {t730w['qty']} in stock, no price (switched off)
--                · STOCK        the stock list's count wins (approved), written only while the
--                               variant still holds 34's figure (sales since then are respected):
--                               A1504VA-BQ541 1 → {a1504['qty']} · Logitech MK270 2 → {mk270['qty']} · Cruzer Blade 16GB 0 → {blade16['qty']}
--                · DETAILS      Blackshadow keyboards: colour Black · Seagate One Touch "2TB Black"
--                               → "2TB" ({ot_total} units, {ot2b['qty']} stated Black) · tag "gaming laptop" on the
--                               sheet's gaming laptops (TUF A18, LOQ 15AHP9, both Cyborg 15s)
-- DEPENDS ON   34_seed_inventory (refuses to run without it).
-- RULES        rows by slug + variant name; marker 'seed_36_inventory_update'; self-verifying.
-- SAFE TO RE-RUN: yes (second run is a no-op).
-- ═════════════════════════════════════════════════════════════════════════════

DO $seed$
DECLARE
  c_marker CONSTANT TEXT := 'seed_36_inventory_update';
  c_note   CONSTANT TEXT := 'From the second stock list ({SHEET2})';
  r        RECORD;
  v_n      INT;
BEGIN
  IF EXISTS (SELECT 1 FROM public.app_config WHERE name = c_marker) THEN
    RAISE NOTICE '36_seed_inventory_update: already applied (app_config %) — skipped', c_marker;
    RETURN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.app_config WHERE name = 'seed_34_inventory') THEN
    RAISE EXCEPTION '36_seed_inventory_update: run 34_seed_inventory.sql first';
  END IF;

  -- ── 1. New product: ASUS VivoBook E1504FA-BQ2909 (no price → its variant starts OFF) ───────
  INSERT INTO public.products (slug, brand, name, category_id, tags, sort_order)
  VALUES ('asus-vivobook-e1504fa-bq2909', 'ASUS', 'ASUS VivoBook E1504FA-BQ2909', 'laptops', ARRAY['laptops']::TEXT[], 135)
  ON CONFLICT (slug) DO NOTHING;

  INSERT INTO public.product_variants (product_id, name, price, position, is_active)
  SELECT p.id, 'Standard', 0, 0, FALSE FROM public.products p WHERE p.slug = 'asus-vivobook-e1504fa-bq2909'
  ON CONFLICT DO NOTHING;

  INSERT INTO public.product_sourcing (product_id, official_title, official_url, wording_type, review_notes)
  SELECT p.id, {q(b['title'])}, {q(b['url'])}, {q(b['wording'])},
         {q(e1504_notes)}
    FROM public.products p WHERE p.slug = 'asus-vivobook-e1504fa-bq2909'
  ON CONFLICT (product_id) DO NOTHING;

  -- ── 2. New variant: JBL Tune 730BT — White (no price → OFF) ────────────────────────────────
  INSERT INTO public.product_variants (product_id, name, option_values, price, position, is_active)
  SELECT p.id, 'White', '{{"Colour":"White"}}'::jsonb, 0, 1, FALSE FROM public.products p WHERE p.slug = 'jbl-tune-730bt'
  ON CONFLICT DO NOTHING;

  -- stock + sourcing for both new variants
  INSERT INTO public.inventory (variant_id, product_id, stock_level)
  SELECT v.id, v.product_id, d.qty
    FROM (VALUES ('asus-vivobook-e1504fa-bq2909', 'Standard', {e1504['qty']}), ('jbl-tune-730bt', 'White', {t730w['qty']})) AS d(slug, name, qty)
    JOIN public.products p ON p.slug = d.slug
    JOIN public.product_variants v ON v.product_id = p.id AND lower(v.name) = lower(d.name)
  ON CONFLICT (variant_id) DO NOTHING;

  INSERT INTO public.variant_sourcing (variant_id, source_category, source_description, colour, price_note)
  SELECT v.id, d.category, d.description, d.colour,
         'No selling price in either stock list — variant switched off until a price is set. ' || c_note || ', row ' || d.row || '.'
    FROM (VALUES
      ('asus-vivobook-e1504fa-bq2909', 'Standard', {q(e1504['type'])}, {q('ASUS VIVOBOOK E1504FA-BQ2909')}, NULL, {e1504['row']}),
      ('jbl-tune-730bt', 'White', {q(t730w['type'])}, {q('JBL OVER HEADPHONE T730 BT - WHITE')}, 'White', {t730w['row']})
    ) AS d(slug, name, category, description, colour, row)
    JOIN public.products p ON p.slug = d.slug
    JOIN public.product_variants v ON v.product_id = p.id AND lower(v.name) = lower(d.name)
  ON CONFLICT (variant_id) DO NOTHING;

  -- ── 3. Stock corrections: only where the stock still holds 34's figure ─────────────────────
  FOR r IN
    SELECT v.id AS variant_id, d.slug, d.name, d.qty, d.old, d.row, i.stock_level
      FROM (VALUES
{stock_vals}
      ) AS d(slug, name, qty, old, row)
      JOIN public.products p ON p.slug = d.slug
      JOIN public.product_variants v ON v.product_id = p.id AND lower(v.name) = lower(d.name)
      JOIN public.inventory i ON i.variant_id = v.id
  LOOP
    IF r.stock_level = r.old THEN
      UPDATE public.inventory SET stock_level = r.qty WHERE variant_id = r.variant_id;
      UPDATE public.variant_sourcing
         SET price_note = concat_ws(' ', price_note,
               format('Stock set to %s from the second stock list (row %s); the first workbook said %s.', r.qty, r.row, r.old))
       WHERE variant_id = r.variant_id;
    ELSE
      RAISE NOTICE '36_seed_inventory_update: % / % stock is % (not 34''s %) — left alone; the stock list says %',
        r.slug, r.name, r.stock_level, r.old, r.qty;
    END IF;
  END LOOP;

  -- ── 4. Details ─────────────────────────────────────────────────────────────────────────────
  UPDATE public.variant_sourcing s SET colour = 'Black'
    FROM public.product_variants v JOIN public.products p ON p.id = v.product_id
   WHERE s.variant_id = v.id AND p.slug = 'blackshadow-keyboard' AND s.colour = 'Not specified';

  UPDATE public.product_variants v SET name = '2TB'
    FROM public.products p
   WHERE p.id = v.product_id AND p.slug = 'seagate-one-touch-portable-hdd' AND v.name = '2TB Black';
  UPDATE public.variant_sourcing s
     SET colour = 'Black ({ot2b['qty']} of {ot_total} units); {ot2['qty']} not specified',
         price_note = concat_ws(' ', price_note, 'The second stock list splits the {ot_total} units: {ot2['qty']} "2TB" (row {ot2['row']}) + {ot2b['qty']} "2TB Black" (row {ot2b['row']}).')
    FROM public.product_variants v JOIN public.products p ON p.id = v.product_id
   WHERE s.variant_id = v.id AND p.slug = 'seagate-one-touch-portable-hdd' AND v.name = '2TB';

  UPDATE public.products SET tags = array_append(tags, 'gaming laptop')
   WHERE slug IN ('asus-tuf-a18-fa808uh-rs74', 'lenovo-loq-15ahp9', 'msi-cyborg-15-core-7-240h', 'msi-cyborg-15-i5-13420h')
     AND NOT ('gaming laptop' = ANY (tags));

  INSERT INTO public.app_config (name, value) VALUES (c_marker, to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SSOF'))
  ON CONFLICT (name) DO NOTHING;

  -- ── 5. Self-verification ───────────────────────────────────────────────────────────────────
  SELECT count(*) INTO v_n
    FROM public.product_variants v JOIN public.products p ON p.id = v.product_id
    JOIN public.inventory i ON i.variant_id = v.id
   WHERE NOT v.is_active AND v.price = 0
     AND ((p.slug = 'asus-vivobook-e1504fa-bq2909' AND v.name = 'Standard' AND i.stock_level = {e1504['qty']})
       OR (p.slug = 'jbl-tune-730bt' AND v.name = 'White' AND i.stock_level = {t730w['qty']}));
  IF v_n <> 2 THEN RAISE EXCEPTION '36_seed_inventory_update: expected the 2 new (switched-off) variants, found %', v_n; END IF;

  SELECT count(*) INTO v_n FROM public.products
   WHERE 'gaming laptop' = ANY (tags) AND slug IN ('asus-tuf-a18-fa808uh-rs74', 'lenovo-loq-15ahp9', 'msi-cyborg-15-core-7-240h', 'msi-cyborg-15-i5-13420h');
  IF v_n <> 4 THEN RAISE EXCEPTION '36_seed_inventory_update: expected 4 gaming-laptop tags, found %', v_n; END IF;

  RAISE NOTICE '36_seed_inventory_update: +1 product, +1 variant ({new_units} units, both awaiting a price), 3 stock corrections, details';
END $seed$;

-- ═════════════════════════════════════════════════════════════════════════════
-- OPS NOTE — 36_seed_inventory_update
--   Price the two new items in admin → Products, then switch their variant on:
--     ASUS VivoBook E1504FA-BQ2909 (whole product stays hidden until then) and JBL Tune 730BT — White.
--   A stock correction that was skipped (because the item sold since 34) is reported as a NOTICE.
-- ═════════════════════════════════════════════════════════════════════════════
"""


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    rows, brand = read(sys.argv[1], sys.argv[2])
    OUT.write_text(build(rows, brand))
    print(f"{OUT.relative_to(ROOT)} written")


if __name__ == "__main__":
    main()
