#!/usr/bin/env python3
"""
Vector logo from the client's artwork (scripts/images/source/dock-one-logo.png: gold on black).

The PNG is traced once with potrace into three pieces — the DO monogram, the "DOCK ONE" name and
the "— SOLUTIONS —" tagline — so the site can draw them at any size and in any colour
(currentColor), and compose them stacked (as supplied) or side by side (header).

Writes:
  src/components/brand/logo-paths.ts   path data for the React components (LogoArt.tsx)
  public/brand/dock-one-logo.svg       stacked lock-up, gold (as supplied, transparent background)
  public/brand/dock-one-mark.svg       DO monogram, gold
  public/brand/dock-one-wordmark.svg   name over tagline, gold

The raster derivatives (favicons, app icons, email header, JSON-LD logo) come from these SVGs:
scripts/images/icons.py. Run this only when the artwork changes:

  python3 -m venv /tmp/logo-venv && /tmp/logo-venv/bin/pip install potracer pillow numpy
  /tmp/logo-venv/bin/python scripts/images/logo.py
"""

from pathlib import Path

import numpy as np
import potrace
from PIL import Image, ImageFilter

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "scripts/images/source/dock-one-logo.png"

# Sampled from the artwork: median of the solid gold pixels.
GOLD = "#e6bd3f"

# Pixel bands of the three pieces in the 665×665 artwork: (top, bottom, left, right), inclusive.
BANDS = {
    "mark": (183, 355, 211, 467),
    "name": (377, 431, 115, 557),
    "tag": (449, 472, 114, 557),
}

# Trace settings, chosen by comparing renders against the artwork: 2× upsample, a light blur to
# even out the PNG's compression noise, potrace's default corner threshold.
UPSAMPLE, BLUR, ALPHAMAX, PAD = 2, 0.8, 1.0, 2


def fmt(value: float) -> str:
    text = f"{value:.2f}".rstrip("0").rstrip(".")
    return "0" if text in ("", "-0") else text


def trace(luma: np.ndarray, gold_luma: float, band: tuple[int, int, int, int]) -> dict:
    top, bottom, left, right = band
    y0, y1, x0, x1 = top - PAD, bottom + PAD + 1, left - PAD, right + PAD + 1
    crop = Image.fromarray(np.clip(luma / gold_luma * 255, 0, 255).astype(np.uint8)[y0:y1, x0:x1])
    big = crop.resize((crop.width * UPSAMPLE, crop.height * UPSAMPLE), Image.Resampling.BICUBIC)
    big = big.filter(ImageFilter.GaussianBlur(UPSAMPLE * BLUR))
    # potracer fills the False pixels: pass "not gold" so the gold shapes are the fill.
    bitmap = potrace.Bitmap(np.asarray(big) <= 127)
    curves = bitmap.trace(
        turdsize=4 * UPSAMPLE * UPSAMPLE,
        turnpolicy=potrace.POTRACE_TURNPOLICY_MINORITY,
        alphamax=ALPHAMAX,
        opticurve=True,
        opttolerance=1.0,
    )

    def pt(p) -> str:
        return f"{fmt(p.x / UPSAMPLE - PAD)} {fmt(p.y / UPSAMPLE - PAD)}"

    parts = []
    for curve in curves:
        d = [f"M{pt(curve.start_point)}"]
        for seg in curve.segments:
            d.append(f"L{pt(seg.c)}L{pt(seg.end_point)}" if seg.is_corner else f"C{pt(seg.c1)} {pt(seg.c2)} {pt(seg.end_point)}")
        parts.append("".join(d) + "Z")
    return {"x": left, "y": top, "w": right - left + 1, "h": bottom - top + 1, "d": "".join(parts)}


def svg(width: int, height: int, body: str) -> str:
    return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" fill="{GOLD}">{body}</svg>\n'


def main() -> None:
    rgb = np.asarray(Image.open(SOURCE).convert("RGB")).astype(float)
    luma = 0.299 * rgb[..., 0] + 0.587 * rgb[..., 1] + 0.114 * rgb[..., 2]
    gold_luma = float(np.median(luma[luma > 170]))
    pieces = {key: trace(luma, gold_luma, band) for key, band in BANDS.items()}
    mark, name, tag = pieces["mark"], pieces["name"], pieces["tag"]

    # Wordmark = name over tagline, as spaced in the artwork.
    word_x = min(name["x"], tag["x"])
    word_w = max(name["x"] + name["w"], tag["x"] + tag["w"]) - word_x
    word_h = tag["y"] + tag["h"] - name["y"]
    name_at = (name["x"] - word_x, 0)
    tag_at = (tag["x"] - word_x, tag["y"] - name["y"])

    # Stacked lock-up = monogram over wordmark, as supplied.
    lock_x, lock_y = word_x, mark["y"]
    lock_w, lock_h = word_w, tag["y"] + tag["h"] - mark["y"]
    mark_at = (mark["x"] - lock_x, 0)
    word_at = (0, name["y"] - mark["y"])

    out = ROOT / "src/components/brand/logo-paths.ts"
    out.write_text(
        "// Generated by scripts/images/logo.py from scripts/images/source/dock-one-logo.png. Do not edit.\n"
        "// Pieces of the Dock One Solutions logo in artwork pixels; LogoArt.tsx composes them.\n\n"
        f'export const LOGO_GOLD = "{GOLD}";\n\n'
        f"export const MARK = {{ w: {mark['w']}, h: {mark['h']}, d: \"{mark['d']}\" }} as const;\n\n"
        f"export const NAME = {{ w: {name['w']}, h: {name['h']}, d: \"{name['d']}\" }} as const;\n\n"
        f"export const TAG = {{ w: {tag['w']}, h: {tag['h']}, d: \"{tag['d']}\" }} as const;\n\n"
        "/** Name over tagline. */\n"
        f"export const WORDMARK = {{ w: {word_w}, h: {word_h}, name: [{name_at[0]}, {name_at[1]}], tag: [{tag_at[0]}, {tag_at[1]}] }} as const;\n\n"
        "/** Monogram over wordmark (the supplied lock-up). */\n"
        f"export const LOCKUP = {{ w: {lock_w}, h: {lock_h}, mark: [{mark_at[0]}, {mark_at[1]}], wordmark: [{word_at[0]}, {word_at[1]}] }} as const;\n"
    )
    print(f"{out.relative_to(ROOT)}  {out.stat().st_size} B")

    def g(x: float, y: float, d: str) -> str:
        return f'<path transform="translate({fmt(x)} {fmt(y)})" d="{d}"/>' if (x or y) else f'<path d="{d}"/>'

    wordmark_body = g(*name_at, name["d"]) + g(*tag_at, tag["d"])
    files = {
        "dock-one-mark.svg": svg(mark["w"], mark["h"], g(0, 0, mark["d"])),
        "dock-one-wordmark.svg": svg(word_w, word_h, wordmark_body),
        "dock-one-logo.svg": svg(
            lock_w,
            lock_h,
            g(*mark_at, mark["d"]) + f'<g transform="translate({fmt(word_at[0])} {fmt(word_at[1])})">{wordmark_body}</g>',
        ),
    }
    for filename, content in files.items():
        path = ROOT / "public/brand" / filename
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"{path.relative_to(ROOT)}  {path.stat().st_size} B")


if __name__ == "__main__":
    main()
