-- ═════════════════════════════════════════════════════════════════════════════
-- 34_seed_inventory.sql — Dock One Solutions
-- GENERATED by scripts/db/inventory/build_seed.py from the client's handoff workbook
-- Dock_One_Combined_Inventory.xlsx. Do not hand-edit — change the script and re-run it.
--
-- PURPOSE      The store's REAL catalogue: 59 products / 86 variants from the workbook's
--              86 stock rows, with selling prices, stock levels and the brand-match notes.
--                · 5 new storefront departments (the sheet's 20 categories grouped — approved), the
--                  four existing ones kept; "Mice" becomes "Mice & Mousepads" if still unrenamed.
--                · rows that differ only by colour / size / capacity / switch / GPU are ONE product
--                  with priced variants (option_values); each variant has its own stock.
--                · price = "Final Selling"; a range ("215,000-220,000") uses the LOWER figure.
--                · stock = "Quantity" (an inventory row per variant, low-stock warning at 3).
--                · the 16 DEMO products and their 4 demo collections are switched OFF
--                  (is_active = FALSE), not deleted — turn any back on in the admin if wanted.
--              Not filled (left for the owner — nothing invented): photos, descriptions, warranty,
--              SKUs, category stage images/hero products, merchandising flags (new / best seller /
--              flash deal / featured). Product pages show the brand's short verbatim excerpt as a
--              highlight where the workbook has one.
-- ADDS         two ADMIN-ONLY tables for what the workbook has and the schema had no place for:
--                product_sourcing  (per product)  official brand title, brand page URL, wording
--                                                  type, review notes (incl. HOLD items)
--                variant_sourcing  (per variant)  workbook row, sheet category, original source
--                                                  description, colour / other-variant text,
--                                                  dealer price (filled by 35), price note
--              Kept out of product_costs on purpose: the admin's "clear cost" deletes that row.
-- DEPENDS ON   01, 02 (is_admin), 04, 05, 30 (the demo slugs it hides).
-- ENABLES      35_seed_inventory_costs (cost + dealer prices, kept out of git).
-- RULES        rows by slug + variant name only (never SERIAL ids); ON CONFLICT DO NOTHING; one
--              atomic DO block behind the app_config marker 'seed_34_inventory'; self-verifying.
-- SAFE TO RE-RUN: yes (second run is a no-op; the demo products are hidden only on the first run).
-- ═════════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Admin-only sourcing tables (the workbook fields the schema had no column for)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.product_sourcing (
  product_id     INT PRIMARY KEY REFERENCES public.products (id) ON DELETE CASCADE,
  official_title TEXT,                      -- the brand's own product title / model label
  official_url   TEXT,                      -- the brand page the match was made against
  wording_type   TEXT,                      -- workbook: how far the brand wording was verified
  review_notes   TEXT,                      -- engineer notes; "HOLD:" = confirm before publishing
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT product_sourcing_lengths CHECK (
        (official_title IS NULL OR char_length(official_title) <= 300)
    AND (official_url   IS NULL OR (char_length(official_url) <= 2000 AND official_url ~ '^https://'))
    AND (wording_type   IS NULL OR char_length(wording_type) <= 120)
    AND (review_notes   IS NULL OR char_length(review_notes) <= 4000))
);

CREATE TABLE IF NOT EXISTS public.variant_sourcing (
  variant_id         INT PRIMARY KEY REFERENCES public.product_variants (id) ON DELETE CASCADE,
  source_row         INT,                   -- row number in the workbook's "Combined Inventory" sheet
  source_category    TEXT,                  -- the sheet's category (e.g. "Gaming Combos", "Internal SSD")
  source_description TEXT,                  -- the original stock-list text, verbatim
  colour             TEXT,                  -- the sheet's Color column ("Not specified" kept as-is)
  other_variant      TEXT,                  -- the sheet's Other variant column
  dealer_price       NUMERIC(12,2),         -- "Dealer Selling" (35_seed_inventory_costs)
  price_note         TEXT,                  -- e.g. the original selling-price range
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT variant_sourcing_dealer_valid CHECK (dealer_price IS NULL OR dealer_price >= 0),
  CONSTRAINT variant_sourcing_lengths CHECK (
        (source_category    IS NULL OR char_length(source_category)    <= 120)
    AND (source_description IS NULL OR char_length(source_description) <= 1000)
    AND (colour             IS NULL OR char_length(colour)             <= 120)
    AND (other_variant      IS NULL OR char_length(other_variant)      <= 200)
    AND (price_note         IS NULL OR char_length(price_note)         <= 1000))
);

DROP TRIGGER IF EXISTS product_sourcing_touch ON public.product_sourcing;
CREATE TRIGGER product_sourcing_touch BEFORE UPDATE ON public.product_sourcing
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
DROP TRIGGER IF EXISTS variant_sourcing_touch ON public.variant_sourcing;
CREATE TRIGGER variant_sourcing_touch BEFORE UPDATE ON public.variant_sourcing
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- Same seal as product_costs: never anon, admins only through RLS, nobody TRUNCATEs via the API.
ALTER TABLE public.product_sourcing ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.variant_sourcing ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.product_sourcing, public.variant_sourcing FROM anon;
REVOKE TRUNCATE, REFERENCES, TRIGGER ON public.product_sourcing, public.variant_sourcing FROM authenticated;
DROP POLICY IF EXISTS product_sourcing_admin_all ON public.product_sourcing;
CREATE POLICY product_sourcing_admin_all ON public.product_sourcing
  FOR ALL TO authenticated USING ((SELECT public.is_admin())) WITH CHECK ((SELECT public.is_admin()));
DROP POLICY IF EXISTS variant_sourcing_admin_all ON public.variant_sourcing;
CREATE POLICY variant_sourcing_admin_all ON public.variant_sourcing
  FOR ALL TO authenticated USING ((SELECT public.is_admin())) WITH CHECK ((SELECT public.is_admin()));

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. The catalogue
-- ─────────────────────────────────────────────────────────────────────────────

DO $seed$
DECLARE
  c_marker CONSTANT TEXT := 'seed_34_inventory';
  c_slugs  CONSTANT TEXT[] := ARRAY[
    'hp-laptop-15-fd0133wm', 'hp-omnibook-16-by0015dx', 'lenovo-v15-g4-83a1011jak',
    'acer-aspire-go-15-ag15-42p-r917', 'dell-inspiron-ldc15255-a117blk-pus', 'asus-vivobook-a1504va-bq541',
    'acer-aspire-lite-al15-53p-58sy', 'asus-vivobook-x1607qa-ls56', 'asus-vivobook-14-flip-tp3407sa',
    'lenovo-loq-15ahp9', 'msi-cyborg-15-core-7-240h', 'msi-cyborg-15-i5-13420h',
    'asus-tuf-a18-fa808uh-rs74', 'kgaming-kg25dhi-280hz-25-gaming-monitor', 'vision-forge-v1-4k-27-dual-mode-gaming-monitor',
    'vision-forge-v1-4k-32-gaming-monitor', 'kgaming-arctic-rift-tri-mode-gaming-keyboard', 'iron-hawk-tri-mode-gaming-keyboard',
    '4-in-1-gaming-combo-pack', 'blackshadow-keyboard', 'logitech-mk270-wireless-keyboard-mouse-combo',
    'logitech-mk295-silent-wireless-combo', 'logitech-m185-wireless-mouse', 'kgaming-aura-strike-rgb-wired-gaming-mouse',
    'kgaming-space-star-rgb-wired-gaming-mouse', 'kgaming-glide-mousepad-cyborg', 'kgaming-glide-mousepad-drakon',
    'kgaming-glide-mousepad-white', 'fujifilm-instax-mini-12', 'fujifilm-instax-mini-se',
    'fujifilm-instax-mini-link-3', 'fujifilm-instax-mini-film', 'anker-nano-charger-45w-a121d',
    'anker-322-usb-c-to-usb-c-cable-3ft', 'anker-nylon-usb-c-to-usb-c-cable-3ft-a8752', 'anker-maggo-magnetic-wireless-charger',
    'anker-533-power-bank-10k-30w', 'anker-zolo-power-bank-25k-165w', 'anker-737-power-bank-24k-140w',
    'anker-soundcore-life-q30', 'jbl-live-770nc', 'jbl-tune-730bt',
    'jbl-tune-770nc', 'jbl-tune-780nc', 'lexar-ns100-sata-ssd',
    'lexar-nm620-m2-nvme-ssd', 'wd-my-passport-portable-hdd', 'seagate-expansion-portable-hdd',
    'seagate-one-touch-portable-hdd', 'sandisk-portable-ssd-1tb-e10', 'sandisk-portable-ssd-v3-e31',
    'sandisk-extreme-portable-ssd-ps5-e62p', 'kingston-xs1000-portable-ssd', 'sandisk-ultra-dual-drive-go-usb-c',
    'sandisk-ultra-dual-drive-luxe-usb-c', 'sandisk-cruzer-blade-cz50', 'sandisk-cruzer-glide-cz600',
    'tp-link-tl-wn823n-mini-wireless-usb-adapter', 'kingston-16gb-ddr5-5600-desktop-ram'];
  c_demo   CONSTANT TEXT[] := ARRAY[
    'vanta-g15-gaming-laptop', 'aeroslim-14-ultrabook', 'forge-studio-16-creator-laptop', 'campus-13-everyday-laptop',
    'bolt-x-portable-ssd-1tb', 'atlas-slim-external-hdd-2tb', 'duolink-flash-drive-128gb', 'vault-desktop-backup-drive-8tb',
    'kairo-75-wireless-mechanical-keyboard', 'onyx-pro-full-size-rgb-keyboard', 'feather-slim-wireless-keyboard', 'volt-60-compact-keyboard-acid-lime',
    'glide-mx-ergonomic-wireless-mouse', 'aero-lite-gaming-mouse-58g', 'grip-vertical-ergonomic-mouse', 'pebble-go-travel-mouse'];
  c_demo_collections CONSTANT TEXT[] := ARRAY['work-from-home', 'gaming-zone', 'campus-kit', 'creator-studio'];
  v_bad    TEXT;
  v_n      INT;
  v_sum    BIGINT;
BEGIN
  IF EXISTS (SELECT 1 FROM public.app_config WHERE name = c_marker) THEN
    RAISE NOTICE '34_seed_inventory: already applied (app_config %) — skipped', c_marker;
    RETURN;
  END IF;

  -- ── 2a. Departments: five new ones; the four existing keep the owner's copy ─────────────────
  INSERT INTO public.categories (id, name, tagline, scene, sort_order)
  VALUES
    ('monitors', 'Monitors', 'Gaming monitors, 25 to 32 inch', 'night', 50),
    ('audio', 'Audio', 'Over-ear headphones', 'violet', 60),
    ('power-charging', 'Power & Charging', 'Chargers, cables, wireless chargers & power banks', 'lime', 70),
    ('cameras', 'Cameras & Instax', 'Instant cameras, photo printers & film', 'paper', 80),
    ('components', 'Networking & Components', 'Wi-Fi adapters & desktop RAM', 'paper', 90)
  ON CONFLICT (id) DO NOTHING;
  UPDATE public.categories SET name = 'Mice & Mousepads', tagline = 'Gaming & wireless mice, mousepads'
   WHERE id = 'mice' AND name = 'Mice';

  -- ── 2b. The demo catalogue goes dark (reversible: admin → Products → Active) ────────────────
  UPDATE public.products SET is_active = FALSE WHERE slug = ANY (c_demo) AND is_active;
  UPDATE public.collections SET is_active = FALSE WHERE id = ANY (c_demo_collections) AND is_active;

  -- ── 2c. Products (price columns derive from the variants in 2d) ─────────────────────────────
  INSERT INTO public.products (slug, brand, name, subtitle, category_id, tags, attributes, sort_order)
  SELECT d.slug, d.brand, d.name, d.subtitle, d.category_id, d.tags, d.attributes, d.sort_order
    FROM (VALUES
      ('hp-laptop-15-fd0133wm', 'HP', 'HP Laptop 15-fd0133wm', 'Core i3-N305 · 8GB · 256GB SSD · 15.6" FHD · Windows 11', 'laptops', ARRAY['laptops']::TEXT[], '{"specs": {"cpu": "Intel Core i3-N305", "ram_gb": 8, "storage_gb": 256, "storage_type": "SSD", "display": "15.6-inch FHD", "os": "Windows 11"}}'::jsonb, 10),
      ('hp-omnibook-16-by0015dx', 'HP', 'HP OmniBook 16-by0015dx', 'Ryzen 5 · 8GB · 256GB SSD · 16" touch · Windows 11', 'laptops', ARRAY['laptops']::TEXT[], '{"specs": {"cpu": "AMD Ryzen 5", "ram_gb": 8, "storage_gb": 256, "storage_type": "SSD", "display": "16-inch touch", "os": "Windows 11"}}'::jsonb, 20),
      ('lenovo-v15-g4-83a1011jak', 'Lenovo', 'Lenovo V15 G4 (83A1011JAK)', 'Core i3-1315U · 8GB · 256GB SSD · 15.6" FHD · DOS', 'laptops', ARRAY['laptops']::TEXT[], '{"specs": {"cpu": "Intel Core i3-1315U", "ram_gb": 8, "storage_gb": 256, "storage_type": "SSD", "display": "15.6-inch FHD", "os": "DOS"}}'::jsonb, 30),
      ('acer-aspire-go-15-ag15-42p-r917', 'Acer', 'Acer Aspire Go 15 AG15-42P-R917', NULL, 'laptops', ARRAY['laptops']::TEXT[], '{}'::jsonb, 40),
      ('dell-inspiron-ldc15255-a117blk-pus', 'Dell', 'Dell Inspiron LDC15255-A117BLK-PUS', NULL, 'laptops', ARRAY['laptops']::TEXT[], '{}'::jsonb, 50),
      ('asus-vivobook-a1504va-bq541', 'ASUS', 'ASUS VivoBook A1504VA-BQ541', 'Core 5 120U · 8GB DDR5 · 512GB SSD · 15.6" FHD', 'laptops', ARRAY['laptops']::TEXT[], '{"specs": {"cpu": "Intel Core 5 120U", "ram_gb": 8, "storage_gb": 512, "storage_type": "SSD", "display": "15.6-inch FHD"}}'::jsonb, 60),
      ('acer-aspire-lite-al15-53p-58sy', 'Acer', 'Acer Aspire Lite AL15-53P-58SY', 'Core 5 120U · 16GB · 512GB SSD · 15.6"', 'laptops', ARRAY['laptops']::TEXT[], '{"specs": {"cpu": "Intel Core 5 120U", "ram_gb": 16, "storage_gb": 512, "storage_type": "SSD", "display": "15.6-inch"}}'::jsonb, 70),
      ('asus-vivobook-x1607qa-ls56', 'ASUS', 'ASUS VivoBook X1607QA-LS56', 'Snapdragon X X1-26-100 · 16GB DDR5 · 1TB SSD · 16"', 'laptops', ARRAY['laptops']::TEXT[], '{"specs": {"cpu": "Qualcomm Snapdragon X X1-26-100", "ram_gb": 16, "storage_gb": 1000, "storage_type": "SSD", "display": "16-inch"}}'::jsonb, 80),
      ('asus-vivobook-14-flip-tp3407sa', 'ASUS', 'ASUS VivoBook 14 Flip TP3407SA', 'Core Ultra 7 256V · 16GB · 1TB SSD · 14" touch', 'laptops', ARRAY['laptops']::TEXT[], '{"specs": {"cpu": "Intel Core Ultra 7 256V", "ram_gb": 16, "storage_gb": 1000, "storage_type": "SSD", "display": "14-inch touch"}}'::jsonb, 90),
      ('lenovo-loq-15ahp9', 'Lenovo', 'Lenovo LOQ 15AHP9', 'Ryzen 7 7445HS · RTX 3050 6GB · 16GB DDR5 · 512GB SSD · 15.6"', 'laptops', ARRAY['laptops']::TEXT[], '{"specs": {"cpu": "AMD Ryzen 7 7445HS", "gpu": "NVIDIA GeForce RTX 3050 (6GB)", "ram_gb": 16, "storage_gb": 512, "storage_type": "SSD", "display": "15.6-inch"}}'::jsonb, 100),
      ('msi-cyborg-15-core-7-240h', 'MSI', 'MSI Cyborg 15 Gaming (Core 7 240H)', 'Core 7 240H · 16GB · 1TB SSD · 15.6"', 'laptops', ARRAY['laptops']::TEXT[], '{"specs": {"cpu": "Intel Core 7 240H", "gpu": "NVIDIA GeForce RTX 5060 (8GB)", "ram_gb": 16, "storage_gb": 1000, "storage_type": "SSD", "display": "15.6-inch"}, "use_cases": ["gaming"]}'::jsonb, 110),
      ('msi-cyborg-15-i5-13420h', 'MSI', 'MSI Cyborg 15 (Core i5-13420H)', 'Core i5-13420H · RTX 4050 6GB · 16GB · 512GB SSD · 15.6"', 'laptops', ARRAY['laptops']::TEXT[], '{"specs": {"cpu": "Intel Core i5-13420H", "gpu": "NVIDIA GeForce RTX 4050 (6GB)", "ram_gb": 16, "storage_gb": 512, "storage_type": "SSD", "display": "15.6-inch"}}'::jsonb, 120),
      ('asus-tuf-a18-fa808uh-rs74', 'ASUS', 'ASUS TUF A18 FA808UH-RS74', 'Ryzen 7 260 · RTX 5050 8GB · 16GB DDR5 · 1TB SSD · 18"', 'laptops', ARRAY['laptops']::TEXT[], '{"specs": {"cpu": "AMD Ryzen 7 260", "gpu": "NVIDIA GeForce RTX 5050 (8GB)", "ram_gb": 16, "storage_gb": 1000, "storage_type": "SSD", "display": "18-inch"}}'::jsonb, 130),
      ('kgaming-kg25dhi-280hz-25-gaming-monitor', 'KGaming', 'KGaming KG25DHI 280Hz 25" Gaming Monitor', '25-inch · 280Hz', 'monitors', ARRAY['monitors']::TEXT[], '{"specs": {"display": "25-inch", "refresh_hz": 280}, "use_cases": ["gaming"]}'::jsonb, 140),
      ('vision-forge-v1-4k-27-dual-mode-gaming-monitor', 'KGaming', 'Vision Forge V1 4K 27-inch Dual Mode Gaming Monitor', '27-inch · 4K · Dual mode', 'monitors', ARRAY['monitors']::TEXT[], '{"specs": {"display": "27-inch 4K"}, "use_cases": ["gaming"]}'::jsonb, 150),
      ('vision-forge-v1-4k-32-gaming-monitor', 'KGaming', 'Vision Forge V1 4K 32-inch Gaming Monitor', '32-inch · 4K', 'monitors', ARRAY['monitors']::TEXT[], '{"specs": {"display": "32-inch 4K"}, "use_cases": ["gaming"]}'::jsonb, 160),
      ('kgaming-arctic-rift-tri-mode-gaming-keyboard', 'KGaming', 'KGaming Arctic Rift Tri-Mode Gaming Keyboard', 'Tri-mode · Wired, Bluetooth & 2.4GHz', 'keyboards', ARRAY['keyboards']::TEXT[], '{"specs": {"connectivity": ["Wired", "Bluetooth", "2.4GHz wireless"]}, "highlights": ["Wired, Bluetooth, and 2.4GHz connectivity"], "use_cases": ["gaming"]}'::jsonb, 170),
      ('iron-hawk-tri-mode-gaming-keyboard', 'KGaming', 'Iron Hawk Tri-Mode Gaming Keyboard', 'Tri-mode gaming keyboard', 'keyboards', ARRAY['keyboards']::TEXT[], '{"use_cases": ["gaming"]}'::jsonb, 180),
      ('4-in-1-gaming-combo-pack', 'KGaming', '4-in-1 Gaming Combo Pack (Mouse, Mousepad, Keyboard, Headset)', 'Mouse · Mousepad · Keyboard · Headset', 'keyboards', ARRAY['gaming combos']::TEXT[], '{"use_cases": ["gaming"]}'::jsonb, 190),
      ('blackshadow-keyboard', 'KGaming', 'Blackshadow Keyboard', NULL, 'keyboards', ARRAY['keyboards']::TEXT[], '{}'::jsonb, 200),
      ('logitech-mk270-wireless-keyboard-mouse-combo', 'Logitech', 'Logitech MK270 Wireless Keyboard and Mouse Combo', 'Wireless · Full-size · 920-004519', 'keyboards', ARRAY['keyboards']::TEXT[], '{"specs": {"layout": "Full-size", "connectivity": ["Wireless"]}, "highlights": ["Full-size wireless combo"]}'::jsonb, 210),
      ('logitech-mk295-silent-wireless-combo', 'Logitech', 'Logitech MK295 Silent Wireless Combo', 'Wireless · Silent · 920-009801', 'keyboards', ARRAY['keyboards']::TEXT[], '{"specs": {"connectivity": ["Wireless"]}}'::jsonb, 220),
      ('logitech-m185-wireless-mouse', 'Logitech', 'Logitech M185 Wireless Mouse', 'Wireless · 910-002235', 'mice', ARRAY['mice']::TEXT[], '{"specs": {"connectivity": ["Wireless"]}}'::jsonb, 230),
      ('kgaming-aura-strike-rgb-wired-gaming-mouse', 'KGaming', 'KGaming Aura Strike RGB Wired Gaming Mouse', 'RGB · Wired', 'mice', ARRAY['mice']::TEXT[], '{"specs": {"connectivity": ["Wired"], "backlight": "RGB"}, "highlights": ["Designed for precision and durability"], "use_cases": ["gaming"]}'::jsonb, 240),
      ('kgaming-space-star-rgb-wired-gaming-mouse', 'KGaming', 'KGaming Space Star RGB Wired Gaming Mouse', 'RGB · Wired', 'mice', ARRAY['mice']::TEXT[], '{"specs": {"connectivity": ["Wired"], "backlight": "RGB"}, "use_cases": ["gaming"]}'::jsonb, 250),
      ('kgaming-glide-mousepad-cyborg', 'KGaming', 'KGaming Glide Mousepad Cyborg', 'Cyborg design · Large, XL or XXL', 'mice', ARRAY['mousepads']::TEXT[], '{}'::jsonb, 260),
      ('kgaming-glide-mousepad-drakon', 'KGaming', 'KGaming Glide Mousepad Drakon', 'Drakon design · Medium or Large', 'mice', ARRAY['mousepads']::TEXT[], '{}'::jsonb, 270),
      ('kgaming-glide-mousepad-white', 'KGaming', 'KGaming Glide Mousepad White', 'White · Medium', 'mice', ARRAY['mousepads']::TEXT[], '{}'::jsonb, 280),
      ('fujifilm-instax-mini-12', 'Fujifilm', 'Fujifilm instax mini 12', 'Instant camera', 'cameras', ARRAY['instant cameras']::TEXT[], '{"highlights": ["Bright Images with Automatic Exposure"]}'::jsonb, 290),
      ('fujifilm-instax-mini-se', 'Fujifilm', 'Fujifilm instax mini SE', 'Instant camera', 'cameras', ARRAY['instant cameras']::TEXT[], '{"highlights": ["Made to capture moments in any lighting with brightness control."]}'::jsonb, 300),
      ('fujifilm-instax-mini-link-3', 'Fujifilm', 'Fujifilm instax mini Link 3', 'Smartphone photo printer', 'cameras', ARRAY['photo printers']::TEXT[], '{"highlights": ["Bring fun to life with the instax mini Link 3™ Smartphone printer."]}'::jsonb, 310),
      ('fujifilm-instax-mini-film', 'Fujifilm', 'Fujifilm instax mini Film', 'Instant film · 10 or 20 sheets', 'cameras', ARRAY['instant film']::TEXT[], '{}'::jsonb, 320),
      ('anker-nano-charger-45w-a121d', 'Anker', 'Anker Nano Charger 45W (A121D)', '45W · USB-C', 'power-charging', ARRAY['chargers']::TEXT[], '{}'::jsonb, 330),
      ('anker-322-usb-c-to-usb-c-cable-3ft', 'Anker', 'Anker 322 USB-C to USB-C Cable (3ft)', 'USB-C to USB-C · 3ft', 'power-charging', ARRAY['cables']::TEXT[], '{}'::jsonb, 340),
      ('anker-nylon-usb-c-to-usb-c-cable-3ft-a8752', 'Anker', 'Anker Nylon USB-C to USB-C Cable (3ft, A8752)', 'USB-C to USB-C · Nylon · 3ft', 'power-charging', ARRAY['cables']::TEXT[], '{}'::jsonb, 350),
      ('anker-maggo-magnetic-wireless-charger', 'Anker', 'Anker MagGo Magnetic Wireless Charger', 'Magnetic wireless charger', 'power-charging', ARRAY['wireless chargers']::TEXT[], '{}'::jsonb, 360),
      ('anker-533-power-bank-10k-30w', 'Anker', 'Anker 533 Power Bank (10K, 30W)', '10,000mAh · 30W', 'power-charging', ARRAY['power banks']::TEXT[], '{}'::jsonb, 370),
      ('anker-zolo-power-bank-25k-165w', 'Anker', 'Anker Zolo Power Bank (25K, 165W, Built-in Cable)', '25,000mAh · 165W · Built-in cable', 'power-charging', ARRAY['power banks']::TEXT[], '{}'::jsonb, 380),
      ('anker-737-power-bank-24k-140w', 'Anker', 'Anker 737 Power Bank (24K, 140W)', '24,000mAh · 140W', 'power-charging', ARRAY['power banks']::TEXT[], '{"highlights": ["Charge 3 Devices at Once"]}'::jsonb, 390),
      ('anker-soundcore-life-q30', 'Anker', 'Anker Soundcore Life Q30', 'Wireless headphones', 'audio', ARRAY['headphones']::TEXT[], '{}'::jsonb, 400),
      ('jbl-live-770nc', 'JBL', 'JBL Live 770NC', 'Wireless over-ear · Adaptive noise cancelling', 'audio', ARRAY['headphones']::TEXT[], '{"highlights": ["Wireless Over-Ear Headphones with True Adaptive Noise Cancelling"]}'::jsonb, 410),
      ('jbl-tune-730bt', 'JBL', 'JBL Tune 730BT', 'Wireless over-ear', 'audio', ARRAY['headphones']::TEXT[], '{"highlights": ["Wireless over-ear headphones"]}'::jsonb, 420),
      ('jbl-tune-770nc', 'JBL', 'JBL Tune 770NC', 'Wireless over-ear · Adaptive noise cancelling', 'audio', ARRAY['headphones']::TEXT[], '{"highlights": ["Adaptive Noise Cancelling Wireless Over-Ear Headphones"]}'::jsonb, 430),
      ('jbl-tune-780nc', 'JBL', 'JBL Tune 780NC', 'Wireless over-ear · Noise cancelling', 'audio', ARRAY['headphones']::TEXT[], '{"highlights": ["Wireless over-ear Noise Cancelling headphones"]}'::jsonb, 440),
      ('lexar-ns100-sata-ssd', 'Lexar', 'Lexar NS100 2.5" SATA SSD', 'Internal SSD · 2.5" SATA', 'storage', ARRAY['internal ssd']::TEXT[], '{"specs": {"capacity_gb": 128, "type": "Internal SSD", "interface": "2.5\" SATA"}}'::jsonb, 450),
      ('lexar-nm620-m2-nvme-ssd', 'Lexar', 'Lexar NM620 M.2 NVMe SSD', 'Internal SSD · M.2 NVMe Gen3 · 3500MB/s', 'storage', ARRAY['internal ssd']::TEXT[], '{"specs": {"capacity_gb": 256, "type": "Internal SSD", "interface": "M.2 NVMe Gen3", "speed_mbps": 3500}}'::jsonb, 460),
      ('wd-my-passport-portable-hdd', 'WD', 'WD My Passport Portable HDD', 'External HDD', 'storage', ARRAY['external hdd']::TEXT[], '{"specs": {"capacity_gb": 2000, "type": "External HDD"}, "use_cases": ["backup"]}'::jsonb, 470),
      ('seagate-expansion-portable-hdd', 'Seagate', 'Seagate Expansion Portable HDD', 'External HDD · 1TB or 4TB', 'storage', ARRAY['external hdd']::TEXT[], '{"specs": {"capacity_gb": 1000, "type": "External HDD"}}'::jsonb, 480),
      ('seagate-one-touch-portable-hdd', 'Seagate', 'Seagate One Touch Portable HDD', 'External HDD · 1TB or 2TB', 'storage', ARRAY['external hdd']::TEXT[], '{"specs": {"capacity_gb": 1000, "type": "External HDD"}}'::jsonb, 490),
      ('sandisk-portable-ssd-1tb-e10', 'SanDisk', 'SanDisk Portable SSD (SDSSDE10)', 'Portable SSD · 600MB/s', 'storage', ARRAY['external ssd']::TEXT[], '{"specs": {"capacity_gb": 1000, "type": "Portable SSD", "speed_mbps": 600}}'::jsonb, 500),
      ('sandisk-portable-ssd-v3-e31', 'SanDisk', 'SanDisk Portable SSD V3 (E31)', 'Portable SSD · 1000MB/s', 'storage', ARRAY['external ssd']::TEXT[], '{"specs": {"capacity_gb": 2000, "type": "Portable SSD", "speed_mbps": 1000}}'::jsonb, 510),
      ('sandisk-extreme-portable-ssd-ps5-e62p', 'SanDisk', 'SanDisk Extreme Portable SSD for PS5 (E62P)', 'Portable SSD · 1000MB/s · PS5 and PC', 'storage', ARRAY['external ssd']::TEXT[], '{"specs": {"capacity_gb": 1000, "type": "Portable SSD", "speed_mbps": 1000}}'::jsonb, 520),
      ('kingston-xs1000-portable-ssd', 'Kingston', 'Kingston XS1000 Portable SSD', 'Portable SSD', 'storage', ARRAY['external ssd']::TEXT[], '{"specs": {"capacity_gb": 1000, "type": "Portable SSD"}}'::jsonb, 530),
      ('sandisk-ultra-dual-drive-go-usb-c', 'SanDisk', 'SanDisk Ultra Dual Drive Go USB Type-C', 'Flash drive · USB Type-C', 'storage', ARRAY['usb flash drives']::TEXT[], '{"specs": {"capacity_gb": 32, "type": "Flash drive", "interface": "USB Type-C"}}'::jsonb, 540),
      ('sandisk-ultra-dual-drive-luxe-usb-c', 'SanDisk', 'SanDisk Ultra Dual Drive Luxe USB Type-C', 'Flash drive · USB Type-C + Type-A', 'storage', ARRAY['usb flash drives']::TEXT[], '{"specs": {"capacity_gb": 64, "type": "Flash drive", "interface": "USB Type-C + USB Type-A"}, "highlights": ["The all-metal, 2-in-1 flash drive for your USB Type-C™ and Type-A devices"]}'::jsonb, 550),
      ('sandisk-cruzer-blade-cz50', 'SanDisk', 'SanDisk Cruzer Blade USB Flash Drive (CZ50)', 'Flash drive · USB', 'storage', ARRAY['usb flash drives']::TEXT[], '{"specs": {"capacity_gb": 128, "type": "Flash drive"}, "highlights": ["Compact design for maximum portability"]}'::jsonb, 560),
      ('sandisk-cruzer-glide-cz600', 'SanDisk', 'SanDisk Cruzer Glide 3.0 USB Flash Drive (CZ600)', 'Flash drive · USB 3.0', 'storage', ARRAY['usb flash drives']::TEXT[], '{"specs": {"capacity_gb": 16, "type": "Flash drive", "interface": "USB 3.0"}, "highlights": ["Retractable design"]}'::jsonb, 570),
      ('tp-link-tl-wn823n-mini-wireless-usb-adapter', 'TP-Link', 'TP-Link TL-WN823N Mini Wireless USB Adapter', '300Mbps · USB Wi-Fi adapter', 'components', ARRAY['wi-fi adapter']::TEXT[], '{"specs": {"connectivity": ["Wi-Fi 300Mbps"], "interface": "USB"}, "highlights": ["300Mbps Mini Wireless N USB WiFi Adapter"]}'::jsonb, 580),
      ('kingston-16gb-ddr5-5600-desktop-ram', 'Kingston', 'Kingston 16GB DDR5 5600 Desktop RAM', '16GB · DDR5 · 5600 · Desktop', 'components', ARRAY['ram']::TEXT[], '{}'::jsonb, 590)
    ) AS d(slug, brand, name, subtitle, category_id, tags, attributes, sort_order)
  ON CONFLICT (slug) DO NOTHING;

  -- ── 2d. Variants: one per stock row, priced from "Final Selling" ────────────────────────────
  INSERT INTO public.product_variants (product_id, name, option_values, price, position, is_active)
  SELECT p.id, d.name, d.option_values, d.price, d.position, d.is_active
    FROM (VALUES
      ('hp-laptop-15-fd0133wm', 'Standard', '{}'::jsonb, 155000, 0, TRUE),
      ('hp-omnibook-16-by0015dx', 'Standard', '{}'::jsonb, 170000, 0, TRUE),
      ('lenovo-v15-g4-83a1011jak', 'Standard', '{}'::jsonb, 157000, 0, TRUE),
      ('acer-aspire-go-15-ag15-42p-r917', 'Standard', '{}'::jsonb, 245000, 0, TRUE),
      ('dell-inspiron-ldc15255-a117blk-pus', 'Standard', '{}'::jsonb, 245000, 0, TRUE),
      ('asus-vivobook-a1504va-bq541', 'Standard', '{}'::jsonb, 215000, 0, TRUE),
      ('acer-aspire-lite-al15-53p-58sy', 'Standard', '{}'::jsonb, 230000, 0, TRUE),
      ('asus-vivobook-x1607qa-ls56', 'Standard', '{}'::jsonb, 265000, 0, TRUE),
      ('asus-vivobook-14-flip-tp3407sa', 'Standard', '{}'::jsonb, 390000, 0, TRUE),
      ('lenovo-loq-15ahp9', 'Standard', '{}'::jsonb, 350000, 0, TRUE),
      ('msi-cyborg-15-core-7-240h', 'RTX 5060 8GB', '{"Graphics": "RTX 5060 8GB"}'::jsonb, 515000, 0, TRUE),
      ('msi-cyborg-15-core-7-240h', 'RTX 5070 8GB', '{"Graphics": "RTX 5070 8GB"}'::jsonb, 560000, 1, TRUE),
      ('msi-cyborg-15-i5-13420h', 'Standard', '{}'::jsonb, 355000, 0, TRUE),
      ('asus-tuf-a18-fa808uh-rs74', 'Standard', '{}'::jsonb, 515000, 0, TRUE),
      ('kgaming-kg25dhi-280hz-25-gaming-monitor', '25-inch', '{"Size": "25-inch"}'::jsonb, 75000, 0, TRUE),
      ('vision-forge-v1-4k-27-dual-mode-gaming-monitor', '27-inch', '{"Size": "27-inch"}'::jsonb, 115000, 0, TRUE),
      ('vision-forge-v1-4k-32-gaming-monitor', '32-inch', '{"Size": "32-inch"}'::jsonb, 127000, 0, TRUE),
      ('kgaming-arctic-rift-tri-mode-gaming-keyboard', 'Cream Blue switch', '{"Switch": "Cream Blue"}'::jsonb, 19500, 0, TRUE),
      ('iron-hawk-tri-mode-gaming-keyboard', 'Jelly Blue switch', '{"Switch": "Jelly Blue"}'::jsonb, 19500, 0, TRUE),
      ('iron-hawk-tri-mode-gaming-keyboard', 'Jelly Pink switch', '{"Switch": "Jelly Pink"}'::jsonb, 19500, 1, TRUE),
      ('4-in-1-gaming-combo-pack', 'Blue switch', '{"Switch": "Blue"}'::jsonb, 22000, 0, TRUE),
      ('4-in-1-gaming-combo-pack', 'Red switch', '{"Switch": "Red"}'::jsonb, 22000, 1, TRUE),
      ('blackshadow-keyboard', 'Blue switch', '{"Switch": "Blue"}'::jsonb, 12000, 0, TRUE),
      ('blackshadow-keyboard', 'Red switch', '{"Switch": "Red"}'::jsonb, 12000, 1, TRUE),
      ('logitech-mk270-wireless-keyboard-mouse-combo', 'Standard', '{}'::jsonb, 7500, 0, TRUE),
      ('logitech-mk295-silent-wireless-combo', 'Standard', '{}'::jsonb, 7700, 0, TRUE),
      ('logitech-m185-wireless-mouse', 'Standard', '{}'::jsonb, 3500, 0, TRUE),
      ('kgaming-aura-strike-rgb-wired-gaming-mouse', 'Standard', '{}'::jsonb, 5000, 0, TRUE),
      ('kgaming-space-star-rgb-wired-gaming-mouse', 'Standard', '{}'::jsonb, 7500, 0, TRUE),
      ('kgaming-glide-mousepad-cyborg', 'Large', '{"Size": "Large"}'::jsonb, 2900, 0, TRUE),
      ('kgaming-glide-mousepad-cyborg', 'XL', '{"Size": "XL"}'::jsonb, 3800, 1, TRUE),
      ('kgaming-glide-mousepad-cyborg', 'XXL', '{"Size": "XXL"}'::jsonb, 5200, 2, TRUE),
      ('kgaming-glide-mousepad-drakon', 'Medium', '{"Size": "Medium"}'::jsonb, 2400, 0, TRUE),
      ('kgaming-glide-mousepad-drakon', 'Large', '{"Size": "Large"}'::jsonb, 2900, 1, TRUE),
      ('kgaming-glide-mousepad-white', 'Medium', '{"Size": "Medium"}'::jsonb, 2400, 0, TRUE),
      ('fujifilm-instax-mini-12', 'Lilac Purple', '{"Colour": "Lilac Purple"}'::jsonb, 31000, 0, TRUE),
      ('fujifilm-instax-mini-12', 'Mint Green', '{"Colour": "Mint Green"}'::jsonb, 31000, 1, TRUE),
      ('fujifilm-instax-mini-12', 'Pastel Blue', '{"Colour": "Pastel Blue"}'::jsonb, 31000, 2, TRUE),
      ('fujifilm-instax-mini-se', 'Blue', '{"Colour": "Blue"}'::jsonb, 28000, 0, TRUE),
      ('fujifilm-instax-mini-se', 'Pink', '{"Colour": "Pink"}'::jsonb, 28000, 1, TRUE),
      ('fujifilm-instax-mini-link-3', 'Rose Pink', '{"Colour": "Rose Pink"}'::jsonb, 34000, 0, TRUE),
      ('fujifilm-instax-mini-link-3', 'Sage Green', '{"Colour": "Sage Green"}'::jsonb, 34000, 1, TRUE),
      ('fujifilm-instax-mini-film', '10 sheets', '{"Pack": "10 sheets"}'::jsonb, 4000, 0, TRUE),
      ('fujifilm-instax-mini-film', '20 sheets', '{"Pack": "20 sheets"}'::jsonb, 8000, 1, TRUE),
      ('anker-nano-charger-45w-a121d', 'Blue', '{"Colour": "Blue"}'::jsonb, 7500, 0, TRUE),
      ('anker-322-usb-c-to-usb-c-cable-3ft', 'Black', '{"Colour": "Black"}'::jsonb, 1800, 0, TRUE),
      ('anker-322-usb-c-to-usb-c-cable-3ft', 'White', '{"Colour": "White"}'::jsonb, 1800, 1, TRUE),
      ('anker-nylon-usb-c-to-usb-c-cable-3ft-a8752', 'Standard', '{}'::jsonb, 2200, 0, TRUE),
      ('anker-maggo-magnetic-wireless-charger', 'White', '{"Colour": "White"}'::jsonb, 12500, 0, TRUE),
      ('anker-maggo-magnetic-wireless-charger', 'Black', '{"Colour": "Black"}'::jsonb, 12500, 1, TRUE),
      ('anker-533-power-bank-10k-30w', 'Standard', '{}'::jsonb, 16500, 0, TRUE),
      ('anker-zolo-power-bank-25k-165w', 'Standard', '{}'::jsonb, 38000, 0, TRUE),
      ('anker-737-power-bank-24k-140w', 'Standard', '{}'::jsonb, 33000, 0, TRUE),
      ('anker-soundcore-life-q30', 'Black', '{"Colour": "Black"}'::jsonb, 25000, 0, TRUE),
      ('jbl-live-770nc', 'Black', '{"Colour": "Black"}'::jsonb, 34000, 0, TRUE),
      ('jbl-tune-730bt', 'Black', '{"Colour": "Black"}'::jsonb, 17000, 0, TRUE),
      ('jbl-tune-770nc', 'Black', '{"Colour": "Black"}'::jsonb, 25000, 0, TRUE),
      ('jbl-tune-780nc', 'Beige', '{"Colour": "Beige"}'::jsonb, 27000, 0, TRUE),
      ('lexar-ns100-sata-ssd', '128GB', '{"Capacity": "128GB"}'::jsonb, 9800, 0, TRUE),
      ('lexar-nm620-m2-nvme-ssd', '256GB', '{"Capacity": "256GB"}'::jsonb, 17000, 0, TRUE),
      ('wd-my-passport-portable-hdd', '2TB', '{"Capacity": "2TB"}'::jsonb, 43000, 0, TRUE),
      ('seagate-expansion-portable-hdd', '1TB', '{"Capacity": "1TB"}'::jsonb, 35000, 0, TRUE),
      ('seagate-expansion-portable-hdd', '4TB', '{"Capacity": "4TB"}'::jsonb, 60000, 1, TRUE),
      ('seagate-one-touch-portable-hdd', '1TB', '{"Capacity": "1TB"}'::jsonb, 35000, 0, TRUE),
      ('seagate-one-touch-portable-hdd', '2TB Black', '{"Capacity": "2TB"}'::jsonb, 44000, 1, TRUE),
      ('sandisk-portable-ssd-1tb-e10', '1TB', '{"Capacity": "1TB"}'::jsonb, 48000, 0, TRUE),
      ('sandisk-portable-ssd-v3-e31', '2TB', '{"Capacity": "2TB"}'::jsonb, 123000, 0, TRUE),
      ('sandisk-extreme-portable-ssd-ps5-e62p', '1TB', '{"Capacity": "1TB"}'::jsonb, 70000, 0, TRUE),
      ('sandisk-extreme-portable-ssd-ps5-e62p', '2TB', '{"Capacity": "2TB"}'::jsonb, 140000, 1, TRUE),
      ('kingston-xs1000-portable-ssd', '1TB', '{"Capacity": "1TB"}'::jsonb, 50000, 0, TRUE),
      ('sandisk-ultra-dual-drive-go-usb-c', '32GB', '{"Capacity": "32GB"}'::jsonb, 4500, 0, TRUE),
      ('sandisk-ultra-dual-drive-go-usb-c', '64GB', '{"Capacity": "64GB"}'::jsonb, 5000, 1, TRUE),
      ('sandisk-ultra-dual-drive-go-usb-c', '128GB', '{"Capacity": "128GB"}'::jsonb, 7500, 2, TRUE),
      ('sandisk-ultra-dual-drive-go-usb-c', '256GB', '{"Capacity": "256GB"}'::jsonb, 15400, 3, TRUE),
      ('sandisk-ultra-dual-drive-luxe-usb-c', '64GB', '{"Capacity": "64GB"}'::jsonb, 6200, 0, TRUE),
      ('sandisk-ultra-dual-drive-luxe-usb-c', '128GB', '{"Capacity": "128GB"}'::jsonb, 9700, 1, TRUE),
      ('sandisk-ultra-dual-drive-luxe-usb-c', '256GB', '{"Capacity": "256GB"}'::jsonb, 17500, 2, TRUE),
      ('sandisk-ultra-dual-drive-luxe-usb-c', '1TB', '{"Capacity": "1TB"}'::jsonb, 69000, 3, TRUE),
      ('sandisk-cruzer-blade-cz50', '16GB', '{"Capacity": "16GB"}'::jsonb, 0, 0, FALSE),
      ('sandisk-cruzer-blade-cz50', '128GB', '{"Capacity": "128GB"}'::jsonb, 4700, 1, TRUE),
      ('sandisk-cruzer-glide-cz600', '16GB', '{"Capacity": "16GB"}'::jsonb, 3500, 0, TRUE),
      ('sandisk-cruzer-glide-cz600', '32GB', '{"Capacity": "32GB"}'::jsonb, 4000, 1, TRUE),
      ('sandisk-cruzer-glide-cz600', '128GB', '{"Capacity": "128GB"}'::jsonb, 5900, 2, TRUE),
      ('sandisk-cruzer-glide-cz600', '256GB', '{"Capacity": "256GB"}'::jsonb, 12500, 3, TRUE),
      ('tp-link-tl-wn823n-mini-wireless-usb-adapter', 'Standard', '{}'::jsonb, 5000, 0, TRUE),
      ('kingston-16gb-ddr5-5600-desktop-ram', 'Standard', '{}'::jsonb, 52000, 0, TRUE)
    ) AS d(slug, name, option_values, price, position, is_active)
    JOIN public.products p ON p.slug = d.slug
  ON CONFLICT DO NOTHING;

  -- ── 2e. Stock: the "Quantity" column, one tracked inventory row per variant ─────────────────
  INSERT INTO public.inventory (variant_id, product_id, stock_level)
  SELECT v.id, v.product_id, d.qty
    FROM (VALUES
      ('hp-laptop-15-fd0133wm', 'Standard', 2),
      ('hp-omnibook-16-by0015dx', 'Standard', 1),
      ('lenovo-v15-g4-83a1011jak', 'Standard', 1),
      ('acer-aspire-go-15-ag15-42p-r917', 'Standard', 3),
      ('dell-inspiron-ldc15255-a117blk-pus', 'Standard', 4),
      ('asus-vivobook-a1504va-bq541', 'Standard', 1),
      ('acer-aspire-lite-al15-53p-58sy', 'Standard', 3),
      ('asus-vivobook-x1607qa-ls56', 'Standard', 1),
      ('asus-vivobook-14-flip-tp3407sa', 'Standard', 2),
      ('lenovo-loq-15ahp9', 'Standard', 1),
      ('msi-cyborg-15-core-7-240h', 'RTX 5060 8GB', 1),
      ('msi-cyborg-15-core-7-240h', 'RTX 5070 8GB', 1),
      ('msi-cyborg-15-i5-13420h', 'Standard', 1),
      ('asus-tuf-a18-fa808uh-rs74', 'Standard', 1),
      ('kgaming-kg25dhi-280hz-25-gaming-monitor', '25-inch', 3),
      ('vision-forge-v1-4k-27-dual-mode-gaming-monitor', '27-inch', 3),
      ('vision-forge-v1-4k-32-gaming-monitor', '32-inch', 3),
      ('kgaming-arctic-rift-tri-mode-gaming-keyboard', 'Cream Blue switch', 3),
      ('iron-hawk-tri-mode-gaming-keyboard', 'Jelly Blue switch', 3),
      ('iron-hawk-tri-mode-gaming-keyboard', 'Jelly Pink switch', 3),
      ('4-in-1-gaming-combo-pack', 'Blue switch', 3),
      ('4-in-1-gaming-combo-pack', 'Red switch', 5),
      ('blackshadow-keyboard', 'Blue switch', 2),
      ('blackshadow-keyboard', 'Red switch', 2),
      ('logitech-mk270-wireless-keyboard-mouse-combo', 'Standard', 2),
      ('logitech-mk295-silent-wireless-combo', 'Standard', 2),
      ('logitech-m185-wireless-mouse', 'Standard', 1),
      ('kgaming-aura-strike-rgb-wired-gaming-mouse', 'Standard', 5),
      ('kgaming-space-star-rgb-wired-gaming-mouse', 'Standard', 5),
      ('kgaming-glide-mousepad-cyborg', 'Large', 3),
      ('kgaming-glide-mousepad-cyborg', 'XL', 3),
      ('kgaming-glide-mousepad-cyborg', 'XXL', 3),
      ('kgaming-glide-mousepad-drakon', 'Medium', 3),
      ('kgaming-glide-mousepad-drakon', 'Large', 3),
      ('kgaming-glide-mousepad-white', 'Medium', 5),
      ('fujifilm-instax-mini-12', 'Lilac Purple', 2),
      ('fujifilm-instax-mini-12', 'Mint Green', 1),
      ('fujifilm-instax-mini-12', 'Pastel Blue', 1),
      ('fujifilm-instax-mini-se', 'Blue', 1),
      ('fujifilm-instax-mini-se', 'Pink', 2),
      ('fujifilm-instax-mini-link-3', 'Rose Pink', 2),
      ('fujifilm-instax-mini-link-3', 'Sage Green', 2),
      ('fujifilm-instax-mini-film', '10 sheets', 8),
      ('fujifilm-instax-mini-film', '20 sheets', 8),
      ('anker-nano-charger-45w-a121d', 'Blue', 4),
      ('anker-322-usb-c-to-usb-c-cable-3ft', 'Black', 4),
      ('anker-322-usb-c-to-usb-c-cable-3ft', 'White', 4),
      ('anker-nylon-usb-c-to-usb-c-cable-3ft-a8752', 'Standard', 4),
      ('anker-maggo-magnetic-wireless-charger', 'White', 4),
      ('anker-maggo-magnetic-wireless-charger', 'Black', 4),
      ('anker-533-power-bank-10k-30w', 'Standard', 3),
      ('anker-zolo-power-bank-25k-165w', 'Standard', 2),
      ('anker-737-power-bank-24k-140w', 'Standard', 2),
      ('anker-soundcore-life-q30', 'Black', 3),
      ('jbl-live-770nc', 'Black', 2),
      ('jbl-tune-730bt', 'Black', 1),
      ('jbl-tune-770nc', 'Black', 3),
      ('jbl-tune-780nc', 'Beige', 3),
      ('lexar-ns100-sata-ssd', '128GB', 5),
      ('lexar-nm620-m2-nvme-ssd', '256GB', 5),
      ('wd-my-passport-portable-hdd', '2TB', 3),
      ('seagate-expansion-portable-hdd', '1TB', 11),
      ('seagate-expansion-portable-hdd', '4TB', 2),
      ('seagate-one-touch-portable-hdd', '1TB', 2),
      ('seagate-one-touch-portable-hdd', '2TB Black', 3),
      ('sandisk-portable-ssd-1tb-e10', '1TB', 2),
      ('sandisk-portable-ssd-v3-e31', '2TB', 2),
      ('sandisk-extreme-portable-ssd-ps5-e62p', '1TB', 10),
      ('sandisk-extreme-portable-ssd-ps5-e62p', '2TB', 8),
      ('kingston-xs1000-portable-ssd', '1TB', 2),
      ('sandisk-ultra-dual-drive-go-usb-c', '32GB', 5),
      ('sandisk-ultra-dual-drive-go-usb-c', '64GB', 5),
      ('sandisk-ultra-dual-drive-go-usb-c', '128GB', 5),
      ('sandisk-ultra-dual-drive-go-usb-c', '256GB', 5),
      ('sandisk-ultra-dual-drive-luxe-usb-c', '64GB', 4),
      ('sandisk-ultra-dual-drive-luxe-usb-c', '128GB', 4),
      ('sandisk-ultra-dual-drive-luxe-usb-c', '256GB', 4),
      ('sandisk-ultra-dual-drive-luxe-usb-c', '1TB', 2),
      ('sandisk-cruzer-blade-cz50', '16GB', 0),
      ('sandisk-cruzer-blade-cz50', '128GB', 2),
      ('sandisk-cruzer-glide-cz600', '16GB', 3),
      ('sandisk-cruzer-glide-cz600', '32GB', 2),
      ('sandisk-cruzer-glide-cz600', '128GB', 2),
      ('sandisk-cruzer-glide-cz600', '256GB', 2),
      ('tp-link-tl-wn823n-mini-wireless-usb-adapter', 'Standard', 7),
      ('kingston-16gb-ddr5-5600-desktop-ram', 'Standard', 3)
    ) AS d(slug, name, qty)
    JOIN public.products p ON p.slug = d.slug
    JOIN public.product_variants v ON v.product_id = p.id AND lower(v.name) = lower(d.name)
  ON CONFLICT (variant_id) DO NOTHING;

  -- ── 2f. Sourcing notes (admin-only) ─────────────────────────────────────────────────────────
  INSERT INTO public.product_sourcing (product_id, official_title, official_url, wording_type, review_notes)
  SELECT p.id, d.official_title, d.official_url, d.wording_type, d.review_notes
    FROM (VALUES
      ('hp-laptop-15-fd0133wm', 'HP 15.6 inch Laptop PC 15-fd0000', 'https://support.hp.com/us-en/product/product-specs/hp-15.6-inch-laptop-pc-15-fd0000/model/2102764694?sku=B4KT4UA', 'Official title / model label only', 'Manufacturer exact model/SKU match.'),
      ('hp-omnibook-16-by0015dx', NULL, 'https://support.hp.com/', 'Unverified - leave blank', 'Exact HP-hosted product description not verified; source model retained. The stock list reads "Ryzen 5 40" — the processor model number looks cut off; confirm it before publishing.'),
      ('lenovo-v15-g4-83a1011jak', 'Lenovo V15 G4 IRU', 'https://psref.lenovo.com/Detail/Lenovo_V15_G4_IRU?M=83A1011JAK', 'Official title / model label only', 'Manufacturer exact model reference.'),
      ('acer-aspire-go-15-ag15-42p-r917', 'Aspire AG15-42P', 'https://www.acer.com/es-es/support/product-support/Aspire_AG15-42P/downloads', 'Official title / model label only', 'Manufacturer model support; R917 configuration not confirmed.'),
      ('dell-inspiron-ldc15255-a117blk-pus', 'Dell 15 DC15255', 'https://www.dell.com/support/product-details/en-uk/product/dell-dc15255-laptop/drivers', 'Official title / model label only', 'Brand model support; source LDC15255-A117BLK-PUS exact configuration needs verification.'),
      ('asus-vivobook-a1504va-bq541', 'ASUS Vivobook 15 (A1504)', 'https://www.asus.com/id/laptops/for-home/vivobook/asus-vivobook-15-a1504/techspec/', 'Official title / model label only', 'Manufacturer family; regional SKU/configuration not confirmed.'),
      ('acer-aspire-lite-al15-53p-58sy', 'Aspire AL15-53P', 'https://www.acer.com/ar-es/support/product-support/Aspire_AL15-53P/downloads', 'Official title / model label only', 'Manufacturer model support; 58SY configuration not confirmed.'),
      ('asus-vivobook-x1607qa-ls56', 'ASUS Vivobook 16 (X1607QA)', 'https://www.asus.com/us/laptops/for-home/vivobook/asus-vivobook-16-x1607q/shop-x1607qa/', 'Official title / model label only', 'Manufacturer family; 512GB/1TB variants. LS56 SKU not confirmed.'),
      ('asus-vivobook-14-flip-tp3407sa', 'TP3407SA', 'https://www.asus.com/in/supportonly/tp3407sa/helpdesk/', 'Official title / model label only', 'Manufacturer model support; exact configuration not confirmed.'),
      ('lenovo-loq-15ahp9', 'LOQ 15AHP9', 'https://psref.lenovo.com/Detail/loq_15ahp9?M=83DX00HNBM', 'Official title / model label only', 'Manufacturer family reference has 1TB; stock lists 512GB. Preserve stock configuration.'),
      ('msi-cyborg-15-core-7-240h', 'Cyborg 15 B2R', 'https://ru.msi.com/Laptop/Cyborg-15-B2RWX/Specification?ysclid=mje5kzb2ln284757321', 'Official title / model label only', 'Manufacturer family lists RTX 5060/5070 variants. Keep GPU variants separate.'),
      ('msi-cyborg-15-i5-13420h', 'Cyborg 15 A13V', 'https://my.msi.com/Laptop/Cyborg-15-A13VX/Specification', 'Official title / model label only', 'Manufacturer family; exact regional SKU not specified.'),
      ('asus-tuf-a18-fa808uh-rs74', 'ASUS TUF Gaming A18 (2025)', 'https://www.asus.com/uk/laptops/for-gaming/tuf-gaming/asus-tuf-gaming-a18-2025/helpdesk_knowledge?model2Name=FA808UH', 'Official title / model label only', 'Manufacturer model support; RS74 configuration not confirmed.'),
      ('kgaming-kg25dhi-280hz-25-gaming-monitor', 'KGAMING KG25DHI-280Hz 25" GAMING MONITOR', 'https://kgaming.co/products/kgaming-kg25dhi-280hz-25-gaming-monitor', 'Official title / model label only', 'Brand product page; 280Hz model.'),
      ('vision-forge-v1-4k-27-dual-mode-gaming-monitor', NULL, 'https://kgaming.co/collections/monitors', 'Unverified - leave blank', 'Exact brand product page not found; retain source name and verify model. Brand not confirmed by the workbook (looked up on kgaming.co); confirm brand and model.'),
      ('vision-forge-v1-4k-32-gaming-monitor', NULL, 'https://kgaming.co/collections/monitors', 'Unverified - leave blank', 'Exact brand product page not found; retain source name and verify model. Brand not confirmed by the workbook (looked up on kgaming.co); confirm brand and model.'),
      ('kgaming-arctic-rift-tri-mode-gaming-keyboard', 'KGAMING (C-MKB96-CB) Arctic Rift Tri-Mode Gaming Keyboard Cream Blue', 'https://kgaming.co/products/kgaming-c-mkb96-cb-arctic-rift-tri-mode-gaming-keyboard-cream-blue', 'Short verbatim excerpt', 'Brand match. Cream Blue is a switch type, not a verified body color.'),
      ('iron-hawk-tri-mode-gaming-keyboard', 'KGAMING (C-MKB96-JB) Arctic Rift Tri-Mode Gaming Keyboard Jelly Blue', 'https://kgaming.co/products/kgaming-c-mkb96-jb-arctic-rift-tri-mode-gaming-keyboard-jelly-blue', 'Official title / model label only', 'HOLD: source says Iron Hawk; brand page says Arctic Rift. Confirm product/model before using brand title. Jelly Blue is a switch type. HOLD: the stock list says Iron Hawk; the matching brand pages (C-MKB96-JB / -JP) say Arctic Rift. Keep the stock name until packaging or the supplier confirms the model.'),
      ('4-in-1-gaming-combo-pack', NULL, 'https://kgaming.co/collections/all', 'Unverified - leave blank', 'Exact brand product page not found. Red/Blue refer to switches, not body color. Brand not confirmed by the workbook (looked up on kgaming.co); confirm brand.'),
      ('blackshadow-keyboard', NULL, 'https://kgaming.co/collections/all', 'Unverified - leave blank', 'Exact brand product page not found. Red/Blue refer to switches, not body color. Brand not confirmed by the workbook (looked up on kgaming.co); confirm brand.'),
      ('logitech-mk270-wireless-keyboard-mouse-combo', 'MK270 Wireless Keyboard and Mouse Combo', 'https://www.logitech.com/en-us/shop/p/mk270-wireless-keyboard-mouse', 'Short verbatim excerpt', 'Manufacturer family page; regional keyboard layout not inferred.'),
      ('logitech-mk295-silent-wireless-combo', 'MK295 Silent Wireless Combo', 'https://www.logitech.com/en-us/shop/p/mk295-keyboard-mouse-combo', 'Official title / model label only', 'Brand family page; verify regional layout/SKU. Color absent in source.'),
      ('logitech-m185-wireless-mouse', 'M185', 'https://www.logitech.com/en-us/shop/p/m185-wireless-mouse?crid=7', 'Official title / model label only', 'Manufacturer family page; source color not specified.'),
      ('kgaming-aura-strike-rgb-wired-gaming-mouse', 'KGAMING (E-GM128) AURA STRIKE RGB Wired Gaming Mouse', 'https://kgaming.co/products/kgaming-e-gm128-aura-strike-rgb-wired-gaming-mouse', 'Short verbatim excerpt', 'Brand product match. RGB is lighting; body color unspecified in source.'),
      ('kgaming-space-star-rgb-wired-gaming-mouse', 'KGAMING (M202) SPACE STAR RGB Wired Gaming Mouse', 'https://kgaming.co/products/kgaming-m202-space-star-rgb-wired-gaming-mouse', 'Official title / model label only', 'Brand product match. RGB is lighting; body color unspecified in source.'),
      ('kgaming-glide-mousepad-cyborg', 'KGAMING Glide Mousepad Cyborg Large', 'https://kgaming.co/products/kgaming-glide-mousepad-cyborg-large', 'Official title / model label only', 'Brand product match; design and size retained.'),
      ('kgaming-glide-mousepad-drakon', 'KGAMING Glide Mousepad Drakon Large', 'https://kgaming.co/products/kgaming-glide-mousepad-drakon-large', 'Official title / model label only', 'Brand product match; design and size retained. Drakon Medium has no verified brand page (Drakon Large does).'),
      ('kgaming-glide-mousepad-white', 'KGAMING Glide Mousepad White Medium', 'https://kgaming.co/products/kgaming-glide-mousepad-white-medium', 'Official title / model label only', 'Brand product match.'),
      ('fujifilm-instax-mini-12', 'instax mini 12™', 'https://www.instax.com/mini_12/en/', 'Short verbatim excerpt', 'Official colors: Pastel Blue, Mint Green, Lilac Purple, Blossom Pink, Clay White. Source colors retained.'),
      ('fujifilm-instax-mini-se', 'instax mini SE™', 'https://www.instaxus.com/cameras/instax-mini-se/', 'Short verbatim excerpt', 'Official variants: blue, pink, green, purple, light gray. Only source-listed colors represent stock.'),
      ('fujifilm-instax-mini-link-3', 'instax mini Link 3™', 'https://www.instaxus.com/printers/instax-mini-link-3/', 'Short verbatim excerpt', 'Official colors: Sage Green, Rose Pink, Clay White. Source Green corresponds to Sage Green.'),
      ('fujifilm-instax-mini-film', 'instax mini', 'https://www.instax.com/film/', 'Official title / model label only', 'Manufacturer film family; retain 10/20-sheet pack distinction.'),
      ('anker-nano-charger-45w-a121d', 'Anker Nano Charger (45W, Smart Display, 180° Foldable)', 'https://www.anker.com/products/a121d-45w-smart-display-charger-dual-foldable?variant=46557402398870', 'Official title / model label only', 'Manufacturer A121D family; regional P31 blue SKU not independently confirmed.'),
      ('anker-322-usb-c-to-usb-c-cable-3ft', 'Anker 322 PowerLine USB-C to USB-C Braided Cable', 'https://anker.com.sg/zh/products/anker-322-powerline-usb-c-to-usb-c-braided-cable-3ft-0-9m-60w-fast-charging-for-usb-c-phones-tablets-laptops-a81f5?_pos=1&_sid=bfab79004&_ss=r', 'Official title / model label only', 'Regional brand page for A81F5 family; retain source Black/WT (White) variants.'),
      ('anker-nylon-usb-c-to-usb-c-cable-3ft-a8752', NULL, 'https://www.anker.tw/ANKER/moreinfo_177767.htm', 'Unverified - leave blank', 'Brand A8752 page located in Chinese; English wording and exact regional SKU require verification.'),
      ('anker-maggo-magnetic-wireless-charger', 'Anker 623 Magnetic Wireless Charger (MagGo)', 'https://service.anker.com/de/article-description/B2568-Anker-623-Magnetic-Wireless-Charger-MagGo-Bedienungsanleitung', 'Official title / model label only', 'Manufacturer B2568 model support; exact regional color SKU not confirmed.'),
      ('anker-533-power-bank-10k-30w', 'Anker 533 Power Bank (PowerCore 30W)', 'https://service.anker.com/product-description/a085g00000Gj24QAAR/anker-533-power-bank-powercore-30w', 'Official title / model label only', 'Manufacturer model match; 10K and 10000mAh are equivalent capacities.'),
      ('anker-zolo-power-bank-25k-165w', 'Anker Power Bank (25K, 165W, Built-in and Retractable Cables)', 'https://service.anker.com/product-description/a08J1000000YR5QIAW', 'Official title / model label only', 'Manufacturer model match; 25K and 25000mAh are equivalent capacities.'),
      ('anker-737-power-bank-24k-140w', 'Anker 737 Power Bank (PowerCore 24K)', 'https://www.anker.com/products/a1289', 'Short verbatim excerpt', 'Manufacturer model match: 24,000mAh / 140W.'),
      ('anker-soundcore-life-q30', 'Life Q30', 'https://www.soundcore.com/products/a3028011?variant=44281589432510', 'Official title / model label only', 'Manufacturer family colors: Black, Midnight Blue, Sakura Pink. Source lists Black.'),
      ('jbl-live-770nc', 'JBL Live 770NC', 'https://www.jbl.com/LIVE770NC.html', 'Short verbatim excerpt', 'Manufacturer model page; preserve source Black variant.'),
      ('jbl-tune-730bt', 'JBL Tune 730BT', 'https://www.jbl.com/TUNE730BT.html/', 'Short verbatim excerpt', 'Manufacturer model page shows Black/White and other colors. Retain source variant.'),
      ('jbl-tune-770nc', 'JBL Tune 770NC', 'https://www.jbl.com/TUNE770NC.html', 'Short verbatim excerpt', 'Manufacturer model page; preserve source Black variant.'),
      ('jbl-tune-780nc', 'JBL Tune 780NC', 'https://www.jbl.com/TUNE780NC.html', 'Short verbatim excerpt', 'Manufacturer match: Tune 780NC Beige, JBLT780NCBEG.'),
      ('lexar-ns100-sata-ssd', 'Lexar® NS100 2.5” SATA III (6Gb/s) SSD', 'https://americas.lexar.com/product/ssd-ns100/', 'Official title / model label only', 'Manufacturer model page includes 128GB.'),
      ('lexar-nm620-m2-nvme-ssd', 'Lexar NM620 M.2 2280 NVMe SSD', 'https://www.lexar.com/global/products/Lexar-NM620-M-2-2280-NVMe-SSD/', 'Official title / model label only', 'Manufacturer model family; source 256GB retained.'),
      ('wd-my-passport-portable-hdd', 'My Passport', 'https://www.westerndigital.com/en-sg/products/portable-drives/wd-my-passport-usb-3-0-hdd', 'Official title / model label only', 'Manufacturer family page; 2TB retained. Source color not specified.'),
      ('seagate-expansion-portable-hdd', 'Expansion Portable', 'https://www.seagate.com/gb/en/support/external-hard-drives/portable-hard-drives/expansion-portable/', 'Official title / model label only', 'Manufacturer family; 1TB/4TB variants retained. Exact SKU not specified.'),
      ('seagate-one-touch-portable-hdd', 'One Touch', 'https://www.seagate.com/products/external-hard-drives/one-touch-external-drives/?bvstate=pg%3A2%2Fct%3Ar&sku=STKY2000400&store=1', 'Official title / model label only', 'Manufacturer family; capacity retained. Exact model/color not inferred where absent.'),
      ('sandisk-portable-ssd-1tb-e10', 'SANDISK Portable Drive (SDSSDE10)', 'https://support-en.sandisk.com/app/products/product-detailweb/p/10329', 'Official title / model label only', 'Manufacturer model support; E10 kept separate from faster E31.'),
      ('sandisk-portable-ssd-v3-e31', 'SANDISK Portable SSD (V3)', 'https://www.sandisk.com/products/ssd/external-ssd/sandisk-portable-ssd-v3?sku=SDSSDE31-500G-G25', 'Official title / model label only', 'Manufacturer family lists 500GB/1TB/2TB. E31 2TB model: SDSSDE31-2T00-G25.'),
      ('sandisk-extreme-portable-ssd-ps5-e62p', 'SANDISK Extreme® Portable SSD for PlayStation®5 Console and PC', 'https://www.sandisk.com/products/ssd/portable-ssd/sandisk-extreme-portable-ssd-ps5?sku=sandisk-extreme-portable-ssd-ps5', 'Official title / model label only', 'Manufacturer confirms 1TB/2TB variants. Ext/External and PS 5/PS5 wording grouped.'),
      ('kingston-xs1000-portable-ssd', 'XS1000 External SSD', 'https://www.kingston.com/en/external-ssd/xs1000-external-solid-state-drive?capacity=1tb', 'Official title / model label only', 'Manufacturer confirms 1TB/2TB and Black/Red variants; stock color not specified.'),
      ('sandisk-ultra-dual-drive-go-usb-c', 'SanDisk Ultra Dual Drive Go USB Type-C™', 'https://www.sandisk.com/es-es/products/usb-flash-drives/sandisk-ultra-dual-drive-go-usb-3-1-type-c?sku=SDDDC3-128G-G46PC', 'Official title / model label only', 'Manufacturer family page; source capacity retained; color not inferred.'),
      ('sandisk-ultra-dual-drive-luxe-usb-c', 'SanDisk Ultra Dual Drive Luxe USB Type-C™ Flash Drive', 'https://www.sandisk.com/products/usb-flash-drives/sandisk-ultra-dual-drive-luxe-usb-3-1-type-c', 'Short verbatim excerpt', 'Manufacturer family page; source capacity retained; color not inferred.'),
      ('sandisk-cruzer-blade-cz50', 'Cruzer Blade USB Flash Drive', 'https://www.sandisk.com/products/usb-flash-drives/sandisk-cruzer-blade-usb-2-0', 'Short verbatim excerpt', 'Manufacturer family page; 16GB/128GB kept separate. 16GB: quantity 0 and no selling price in the stock list, so that variant is switched off until it has a price.'),
      ('sandisk-cruzer-glide-cz600', 'Cruzer Glide 3.0 USB Flash Drive', 'https://www.sandisk.com/products/usb-flash-drives/sandisk-cruzer-glide-usb-3-0', 'Short verbatim excerpt', 'Manufacturer family page; source capacity retained.'),
      ('tp-link-tl-wn823n-mini-wireless-usb-adapter', 'TL-WN823N', 'https://www.tp-link.com/uk/home-networking/adapter/tl-wn823n/', 'Short verbatim excerpt', 'Manufacturer model page; hardware version not specified in stock.'),
      ('kingston-16gb-ddr5-5600-desktop-ram', NULL, 'https://www.kingston.com/en/memory/desktop-laptop', 'Unverified - leave blank', 'HOLD: exact Kingston part number missing. Confirm RAM product line before adding brand description. HOLD: no Kingston part number in the stock list — confirm the RAM product line.')
    ) AS d(slug, official_title, official_url, wording_type, review_notes)
    JOIN public.products p ON p.slug = d.slug
  ON CONFLICT (product_id) DO NOTHING;

  INSERT INTO public.variant_sourcing (variant_id, source_row, source_category, source_description, colour, other_variant, price_note)
  SELECT v.id, d.source_row, d.source_category, d.source_description, d.colour, d.other_variant, d.price_note
    FROM (VALUES
      ('hp-laptop-15-fd0133wm', 'Standard', 6, 'Laptops', 'HP Laptop i3-N305 8GB 256GB SSD 15.6" FHD W11 FPR 15-fd0133wm (B4KT4UA#ABA)', 'Not specified', NULL, NULL),
      ('hp-omnibook-16-by0015dx', 'Standard', 7, 'Laptops', 'HP Laptop Ryzen 5 40 8GB 256GB SSD 16.0"Tch W11 OMNIBOOK 16-by0015dx', 'Not specified', NULL, NULL),
      ('lenovo-v15-g4-83a1011jak', 'Standard', 8, 'Laptops', 'Lenovo Laptop i3-1315U 8GB 256GB SSD 15.6" FHD Dos V15 G4 (83A1011JAK)', 'Not specified', NULL, NULL),
      ('acer-aspire-go-15-ag15-42p-r917', 'Standard', 9, 'Laptops', 'ACER ASPIRE GO 15 AG15-42P-R917', 'Not specified', NULL, NULL),
      ('dell-inspiron-ldc15255-a117blk-pus', 'Standard', 10, 'Laptops', 'DELL INSPIRON LDC15255-A117BLK-PUS', 'Not specified', NULL, NULL),
      ('asus-vivobook-a1504va-bq541', 'Standard', 11, 'Laptops', 'ASUS VivoBook A1504VA-BQ541 Core 5 120U 8GB DDR5 512GB SSD 15.6" FHD', 'Not specified', NULL, 'Final selling range in the stock list: 215,000-220,000 (shop price set to the lower figure).'),
      ('acer-aspire-lite-al15-53p-58sy', 'Standard', 12, 'Laptops', 'Acer Aspire Lite AL15-53P-58SY Core 5 120U 16GB 512GB SSD 15.6"', 'Not specified', NULL, 'Final selling range in the stock list: 230,000-235,000 (shop price set to the lower figure).'),
      ('asus-vivobook-x1607qa-ls56', 'Standard', 13, 'Laptops', 'ASUS VivoBook X1607QA-LS56 Snapdragon X X1-26-100 16GB DDR5 1TB SSD 16"', 'Not specified', NULL, 'Final selling range in the stock list: 265,000-275,000 (shop price set to the lower figure).'),
      ('asus-vivobook-14-flip-tp3407sa', 'Standard', 14, 'Laptops', 'ASUS VivoBook 14 Flip TP3407SA Intel Core Ultra 7 256V 16GB 1TB SSD 14" Touch', 'Not specified', NULL, 'Final selling range in the stock list: 390,000-395,000 (shop price set to the lower figure).'),
      ('lenovo-loq-15ahp9', 'Standard', 15, 'Laptops', 'Lenovo LOQ 15AHP9 Ryzen 7 7445HS 16GB DDR5 512GB SSD 15.6" RTX 3050 6GB', 'Not specified', NULL, 'Final selling range in the stock list: 350,000-355,000 (shop price set to the lower figure).'),
      ('msi-cyborg-15-core-7-240h', 'RTX 5060 8GB', 16, 'Laptops', 'MSI Cyborg 15 Core 7-240H 16GB 1TB SSD 15.6" RTX 5060 8GB', 'Not specified', 'Core 7-240H / RTX 5060 8GB', NULL),
      ('msi-cyborg-15-core-7-240h', 'RTX 5070 8GB', 17, 'Laptops', 'MSI Cyborg 15 Gaming Core 7-240H 16GB DDR5 1TB SSD 15.6" RTX 5070 8GB', 'Not specified', 'Core 7-240H / RTX 5070 8GB', 'Final selling range in the stock list: 560,000-565,000 (shop price set to the lower figure).'),
      ('msi-cyborg-15-i5-13420h', 'Standard', 18, 'Laptops', 'MSI Cyborg 15 i5-13420H 16GB 512GB SSD 15.6" RTX 4050 6GB', 'Not specified', 'i5-13420H / RTX 4050 6GB', 'Final selling range in the stock list: 355,000-370,000 (shop price set to the lower figure).'),
      ('asus-tuf-a18-fa808uh-rs74', 'Standard', 19, 'Laptops', 'ASUS TUF A18 FA808UH-RS74 Ryzen 7-260 16GB DDR5 1TB SSD 18" RTX 5050 8GB', 'Not specified', NULL, 'Final selling range in the stock list: 515,000-520,000 (shop price set to the lower figure).'),
      ('kgaming-kg25dhi-280hz-25-gaming-monitor', '25-inch', 20, 'Monitors', 'KG25DHI-280HZ 25" Gaming Monitor', 'Not specified', '25inch', 'Final selling range in the stock list: 75,000-77,000 (shop price set to the lower figure).'),
      ('vision-forge-v1-4k-27-dual-mode-gaming-monitor', '27-inch', 21, 'Monitors', 'Vision Forge V1 4K 27inch Dual Mode Gaming Monitor', 'Not specified', '27inch', 'Final selling range in the stock list: 115,000-118,000 (shop price set to the lower figure).'),
      ('vision-forge-v1-4k-32-gaming-monitor', '32-inch', 22, 'Monitors', 'Vision Forge V1 4K 32inch Gaming Monitor', 'Not specified', '32inch', 'Final selling range in the stock list: 127,000-127,500 (shop price set to the lower figure).'),
      ('kgaming-arctic-rift-tri-mode-gaming-keyboard', 'Cream Blue switch', 23, 'Keyboards', 'Arctic Rift Tri-Mode Gaming Keyboard Cream Blue', 'Not specified', 'Cream Blue switch', NULL),
      ('iron-hawk-tri-mode-gaming-keyboard', 'Jelly Blue switch', 24, 'Keyboards', 'Iron Hawk Tri-Mode Gaming Keyboard - Jelly Blue', 'Not specified', 'Jelly Blue switch', NULL),
      ('iron-hawk-tri-mode-gaming-keyboard', 'Jelly Pink switch', 25, 'Keyboards', 'Iron Hawk Tri-Mode Gaming Keyboard - Jelly Pink', 'Not specified', 'Jelly Pink switch', NULL),
      ('4-in-1-gaming-combo-pack', 'Blue switch', 26, 'Gaming Combos', '4 in 1 Combo Pack (Mouse, Mousepad, Keyboard, Headset, Blue Switch)', 'Not specified', 'Blue Switch', NULL),
      ('4-in-1-gaming-combo-pack', 'Red switch', 27, 'Gaming Combos', '4 in 1 Combo Pack (Mouse, Mousepad, Keyboard, Headset, Red Switch)', 'Not specified', 'Red Switch', NULL),
      ('blackshadow-keyboard', 'Blue switch', 28, 'Keyboards', 'Keyboard Blackshadow (Blue Switch)', 'Not specified', 'Blue Switch', NULL),
      ('blackshadow-keyboard', 'Red switch', 29, 'Keyboards', 'Keyboard Blackshadow (Red Switch)', 'Not specified', 'Red Switch', NULL),
      ('logitech-mk270-wireless-keyboard-mouse-combo', 'Standard', 30, 'Keyboards', 'Logitech Keyboard Wireless MK270 920-004519', 'Not specified', NULL, NULL),
      ('logitech-mk295-silent-wireless-combo', 'Standard', 31, 'Keyboards', 'Logitech Wireless Keyboard Combo MK295 920-009801', 'Not specified', NULL, NULL),
      ('logitech-m185-wireless-mouse', 'Standard', 32, 'Mice', 'Logitech Wireless Mouse M185 910-002235', 'Not specified', NULL, NULL),
      ('kgaming-aura-strike-rgb-wired-gaming-mouse', 'Standard', 33, 'Mice', 'Aura Strike RGB Wired Gaming Mouse', 'Not specified', NULL, NULL),
      ('kgaming-space-star-rgb-wired-gaming-mouse', 'Standard', 34, 'Mice', 'Space Star RGB Wired Gaming Mouse', 'Not specified', NULL, NULL),
      ('kgaming-glide-mousepad-cyborg', 'Large', 35, 'Mousepads', 'Glide Mousepad Cyborg Large', 'Not specified', 'Cyborg Large', 'Final selling range in the stock list: 2,900-3,000 (shop price set to the lower figure).'),
      ('kgaming-glide-mousepad-cyborg', 'XL', 36, 'Mousepads', 'Glide Mousepad Cyborg XL', 'Not specified', 'Cyborg XL', 'Final selling range in the stock list: 3,800-4,000 (shop price set to the lower figure).'),
      ('kgaming-glide-mousepad-cyborg', 'XXL', 37, 'Mousepads', 'Glide Mousepad Cyborg XXL', 'Not specified', 'Cyborg XXL', 'Final selling range in the stock list: 5,200-5,300 (shop price set to the lower figure).'),
      ('kgaming-glide-mousepad-drakon', 'Medium', 39, 'Mousepads', 'Glide Mousepad Drakon Medium', 'Not specified', 'Drakon Medium', 'Final selling range in the stock list: 2,400-2,500 (shop price set to the lower figure).'),
      ('kgaming-glide-mousepad-drakon', 'Large', 38, 'Mousepads', 'Glide Mousepad Drakon Large', 'Not specified', 'Drakon Large', 'Final selling range in the stock list: 2,900-3,000 (shop price set to the lower figure).'),
      ('kgaming-glide-mousepad-white', 'Medium', 40, 'Mousepads', 'Glide Mousepad White Medium', 'White', 'White Medium', 'Final selling range in the stock list: 2,400-2,500 (shop price set to the lower figure).'),
      ('fujifilm-instax-mini-12', 'Lilac Purple', 41, 'Instant Cameras', 'FUJIFILM INSTAX MINI12 - PURPLE', 'Lilac Purple', NULL, 'Final selling range in the stock list: 31,000-32,000 (shop price set to the lower figure).'),
      ('fujifilm-instax-mini-12', 'Mint Green', 42, 'Instant Cameras', 'FUJIFILM INSTAX MINI12 - GREEN', 'Mint Green', NULL, 'Final selling range in the stock list: 31,000-32,000 (shop price set to the lower figure).'),
      ('fujifilm-instax-mini-12', 'Pastel Blue', 43, 'Instant Cameras', 'FUJIFILM INSTAX MINI12 - BLUE', 'Pastel Blue', NULL, 'Final selling range in the stock list: 31,000-32,000 (shop price set to the lower figure).'),
      ('fujifilm-instax-mini-se', 'Blue', 44, 'Instant Cameras', 'FUJIFILM INSTAX MINI SE BLUE', 'Blue', NULL, 'Final selling range in the stock list: 28,000-29,000 (shop price set to the lower figure).'),
      ('fujifilm-instax-mini-se', 'Pink', 45, 'Instant Cameras', 'FUJIFILM INSTAX MINI SE PINK', 'Pink', NULL, 'Final selling range in the stock list: 28,000-29,000 (shop price set to the lower figure).'),
      ('fujifilm-instax-mini-link-3', 'Rose Pink', 46, 'Photo Printers', 'FUJIFILM INSTAX MINI LINK 3 ROSE PINK', 'Rose Pink', NULL, 'Final selling range in the stock list: 34,000-35,000 (shop price set to the lower figure).'),
      ('fujifilm-instax-mini-link-3', 'Sage Green', 47, 'Photo Printers', 'FUJIFILM INSTAX MINI LINK 3 GREEN', 'Sage Green', NULL, 'Final selling range in the stock list: 34,000-35,000 (shop price set to the lower figure).'),
      ('fujifilm-instax-mini-film', '10 sheets', 48, 'Instant Film', 'FUJIFILM INSTAX MINI FILM 10 SHEET 1 PACK', 'Not specified', '10 SHEET / 1 pack', NULL),
      ('fujifilm-instax-mini-film', '20 sheets', 49, 'Instant Film', 'FUJIFILM INSTAX MINI FILM 20 SHEET 1 PACK', 'Not specified', '20 SHEET / 1 pack', NULL),
      ('anker-nano-charger-45w-a121d', 'Blue', 50, 'Chargers', 'ANKER NANO 45W MAX 1C BLUE A121DP31', 'Blue', NULL, NULL),
      ('anker-322-usb-c-to-usb-c-cable-3ft', 'Black', 51, 'Cables', 'ANKER A81F5H11 BLACK  USB-C TO C CABLE 3FT', 'Black', NULL, 'Final selling range in the stock list: 1,800-2,200 (shop price set to the lower figure).'),
      ('anker-322-usb-c-to-usb-c-cable-3ft', 'White', 52, 'Cables', 'ANKER 322 A81F5H21  WT. USB C TO C 3FT CABLE', 'White', NULL, 'Final selling range in the stock list: 1,800-2,200 (shop price set to the lower figure).'),
      ('anker-nylon-usb-c-to-usb-c-cable-3ft-a8752', 'Standard', 53, 'Cables', 'ANKER NYLON USB C TO USB C CABLE 3FT A8752H11', 'Not specified', NULL, 'Final selling range in the stock list: 2,200-2,500 (shop price set to the lower figure).'),
      ('anker-maggo-magnetic-wireless-charger', 'White', 54, 'Wireless Chargers', 'ANKER MAGNETIC WIRELESS CHARGER MagGO AN.B25682V0', 'White', NULL, NULL),
      ('anker-maggo-magnetic-wireless-charger', 'Black', 55, 'Wireless Chargers', 'ANKER MAGNETIC WIRELESS CHARGER MagGO AN.B25682V1', 'Black', NULL, NULL),
      ('anker-533-power-bank-10k-30w', 'Standard', 56, 'Power Banks', 'ANKER 533 10K MAH 30W POWER BANK A1256H11', 'Not specified', NULL, NULL),
      ('anker-zolo-power-bank-25k-165w', 'Standard', 57, 'Power Banks', 'ANKER ZOLO PB 25KMAH 165W BUILT IN CABLE A1695H11', 'Not specified', NULL, NULL),
      ('anker-737-power-bank-24k-140w', 'Standard', 58, 'Power Banks', 'ANKER A1289011 737 POWER BANK 24K 140W', 'Not specified', NULL, 'Final selling range in the stock list: 33,000-34,000 (shop price set to the lower figure).'),
      ('anker-soundcore-life-q30', 'Black', 59, 'Headphones', 'ANKER SOUNDCORE LIFE Q30 BLACK A3028031', 'Black', NULL, NULL),
      ('jbl-live-770nc', 'Black', 60, 'Headphones', 'JBL LIVE 770NC - BLACK', 'Black', NULL, NULL),
      ('jbl-tune-730bt', 'Black', 61, 'Headphones', 'JBL OVER HEADPHONE T730 BT - BLACK', 'Black', NULL, NULL),
      ('jbl-tune-770nc', 'Black', 62, 'Headphones', 'JBL TUNE T770 NC BLACK', 'Black', NULL, NULL),
      ('jbl-tune-780nc', 'Beige', 63, 'Headphones', 'JBL TUNE 780NC BEIGE', 'Beige', NULL, NULL),
      ('lexar-ns100-sata-ssd', '128GB', 64, 'Internal SSD', 'Lexar SSD 128GB 2.5" NS100', 'Not specified', '128GB', NULL),
      ('lexar-nm620-m2-nvme-ssd', '256GB', 65, 'Internal SSD', 'Lexar SSD 256GB M.2 NVMe Gen3-3500Mbps NM620', 'Not specified', '256GB', NULL),
      ('wd-my-passport-portable-hdd', '2TB', 66, 'External HDD', 'WD 2TB My Passport', 'Not specified', '2TB', NULL),
      ('seagate-expansion-portable-hdd', '1TB', 67, 'External HDD', 'Seagate Expansion - 1TB', 'Not specified', '1TB', NULL),
      ('seagate-expansion-portable-hdd', '4TB', 68, 'External HDD', 'Seagate 4TB Expansion HDD', 'Not specified', '4TB', NULL),
      ('seagate-one-touch-portable-hdd', '1TB', 69, 'External HDD', 'Seagate 1TB One Touch External Hard Disk', 'Not specified', '1TB', NULL),
      ('seagate-one-touch-portable-hdd', '2TB Black', 70, 'External HDD', 'Seagate 2TB External HDD One Touch 2.5" Black', 'Black', '2TB', NULL),
      ('sandisk-portable-ssd-1tb-e10', '1TB', 71, 'External SSD', 'SanDisk 1TB Portable SSD (600MB/s) - SDSSDE10-1T00-G25', 'Not specified', '1TB', NULL),
      ('sandisk-portable-ssd-v3-e31', '2TB', 72, 'External SSD', 'SanDisk External SSD 2TB 2T00-G25 1000 Mbps E31', 'Not specified', '2TB', NULL),
      ('sandisk-extreme-portable-ssd-ps5-e62p', '1TB', 73, 'External SSD', 'SanDisk External SSD Extreme 1TB 1000Mbps E62P (PS5)', 'Not specified', '1TB', NULL),
      ('sandisk-extreme-portable-ssd-ps5-e62p', '2TB', 74, 'External SSD', 'SanDisk External SSD Extreme 2TB 1000Mbps E62P (PS5)', 'Not specified', '2TB', NULL),
      ('kingston-xs1000-portable-ssd', '1TB', 75, 'External SSD', 'Kingston Portable SSD 1TB XS1000', 'Not specified', '1TB', NULL),
      ('sandisk-ultra-dual-drive-go-usb-c', '32GB', 76, 'USB Flash Drives', 'SanDisk 32GB Flash Dual Drive Go Type C', 'Not specified', '32GB', NULL),
      ('sandisk-ultra-dual-drive-go-usb-c', '64GB', 77, 'USB Flash Drives', 'SanDisk 64GB Flash Dual Drive Go Type C', 'Not specified', '64GB', NULL),
      ('sandisk-ultra-dual-drive-go-usb-c', '128GB', 78, 'USB Flash Drives', 'SanDisk 128GB Ultra Dual Drive Go Type C', 'Not specified', '128GB', NULL),
      ('sandisk-ultra-dual-drive-go-usb-c', '256GB', 79, 'USB Flash Drives', 'SanDisk 256GB Flash Dual Drive Go Type C', 'Not specified', '256GB', NULL),
      ('sandisk-ultra-dual-drive-luxe-usb-c', '64GB', 81, 'USB Flash Drives', 'SanDisk 64GB Flash Ultra Luxe Dual Drive', 'Not specified', '64GB', NULL),
      ('sandisk-ultra-dual-drive-luxe-usb-c', '128GB', 82, 'USB Flash Drives', 'SanDisk 128GB Flash Ultra Luxe Dual Drive', 'Not specified', '128GB', NULL),
      ('sandisk-ultra-dual-drive-luxe-usb-c', '256GB', 83, 'USB Flash Drives', 'SanDisk 256GB Flash Ultra Luxe Dual Drive', 'Not specified', '256GB', NULL),
      ('sandisk-ultra-dual-drive-luxe-usb-c', '1TB', 80, 'USB Flash Drives', 'SanDisk 1TB Flash Ultra Luxe Dual Drive', 'Not specified', '1TB', NULL),
      ('sandisk-cruzer-blade-cz50', '16GB', 84, 'USB Flash Drives', 'SanDisk 16GB Flash Cruzer Blade CZ50', 'Not specified', '16GB', 'No selling price in the stock list — variant switched off until a price is set.'),
      ('sandisk-cruzer-blade-cz50', '128GB', 85, 'USB Flash Drives', 'SanDisk 128GB Flash Cruzer Blade CZ50', 'Not specified', '128GB', NULL),
      ('sandisk-cruzer-glide-cz600', '16GB', 86, 'USB Flash Drives', 'SanDisk 16GB Flash Glide USB 3.0 CZ600', 'Not specified', '16GB', NULL),
      ('sandisk-cruzer-glide-cz600', '32GB', 87, 'USB Flash Drives', 'SanDisk 32GB Flash Glide USB 3.0 CZ600', 'Not specified', '32GB', NULL),
      ('sandisk-cruzer-glide-cz600', '128GB', 88, 'USB Flash Drives', 'SanDisk 128GB Flash Glide USB 3.0 CZ600', 'Not specified', '128GB', NULL),
      ('sandisk-cruzer-glide-cz600', '256GB', 89, 'USB Flash Drives', 'SanDisk 256GB Flash Glide USB 3.0 CZ600', 'Not specified', '256GB', NULL),
      ('tp-link-tl-wn823n-mini-wireless-usb-adapter', 'Standard', 90, 'Network Adapter', 'Tplink W/L Mini USB Adaptor 300Mbps Wn823n', 'Not specified', NULL, NULL),
      ('kingston-16gb-ddr5-5600-desktop-ram', 'Standard', 91, 'Internal Storage', 'Kingston RAM 16GB DDR5 Desktop 5600', 'Not specified', NULL, 'Final selling range in the stock list: 52,000-55,000 (shop price set to the lower figure).')
    ) AS d(slug, name, source_row, source_category, source_description, colour, other_variant, price_note)
    JOIN public.products p ON p.slug = d.slug
    JOIN public.product_variants v ON v.product_id = p.id AND lower(v.name) = lower(d.name)
  ON CONFLICT (variant_id) DO NOTHING;

  INSERT INTO public.app_config (name, value) VALUES (c_marker, to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SSOF'))
  ON CONFLICT (name) DO NOTHING;

  -- ── 2g. Self-verification: any failure rolls the whole seed back ────────────────────────────
  SELECT count(*) INTO v_n FROM public.products WHERE slug = ANY (c_slugs);
  IF v_n <> 59 THEN RAISE EXCEPTION '34_seed_inventory: expected 59 products, found %', v_n; END IF;

  SELECT count(*) INTO v_n
    FROM public.product_variants v JOIN public.products p ON p.id = v.product_id
   WHERE p.slug = ANY (c_slugs);
  IF v_n <> 86 THEN RAISE EXCEPTION '34_seed_inventory: expected 86 variants, found %', v_n; END IF;

  SELECT count(*) INTO v_n
    FROM public.product_variants v JOIN public.products p ON p.id = v.product_id
   WHERE p.slug = ANY (c_slugs) AND v.is_active AND v.price > 0;
  IF v_n <> 85 THEN RAISE EXCEPTION '34_seed_inventory: expected 85 priced active variants, found %', v_n; END IF;

  SELECT string_agg(p.slug, ', ') INTO v_bad
    FROM public.products p
   WHERE p.slug = ANY (c_slugs)
     AND (NOT p.is_active OR p.variant_count < 1 OR p.default_variant_id IS NULL OR p.price <= 0 OR p.category_id IS NULL);
  IF v_bad IS NOT NULL THEN RAISE EXCEPTION '34_seed_inventory: products not visible/purchasable: %', v_bad; END IF;

  SELECT count(*), COALESCE(sum(i.stock_level), 0) INTO v_n, v_sum
    FROM public.inventory i JOIN public.products p ON p.id = i.product_id
   WHERE p.slug = ANY (c_slugs);
  IF v_n <> 86 OR v_sum <> 268 THEN
    RAISE EXCEPTION '34_seed_inventory: expected 86 stock rows totalling 268, found % totalling %', v_n, v_sum;
  END IF;

  SELECT count(*) INTO v_n
    FROM public.variant_sourcing s JOIN public.product_variants v ON v.id = s.variant_id
    JOIN public.products p ON p.id = v.product_id
   WHERE p.slug = ANY (c_slugs);
  IF v_n <> 86 THEN RAISE EXCEPTION '34_seed_inventory: expected 86 variant_sourcing rows, found %', v_n; END IF;

  SELECT count(*) INTO v_n FROM public.products WHERE slug = ANY (c_demo) AND is_active;
  IF v_n <> 0 THEN RAISE EXCEPTION '34_seed_inventory: % demo products still active', v_n; END IF;
  SELECT count(*) INTO v_n FROM public.collections WHERE id = ANY (c_demo_collections) AND is_active;
  IF v_n <> 0 THEN RAISE EXCEPTION '34_seed_inventory: % demo collections still active', v_n; END IF;

  RAISE NOTICE '34_seed_inventory: 59 products, 86 variants, 86 stock rows (268 units); demo catalogue + collections hidden';
END $seed$;

-- ═════════════════════════════════════════════════════════════════════════════
-- OPS NOTE — 34_seed_inventory
--   Next: run 35_seed_inventory_costs.sql (cost + dealer prices; kept out of git), then add photos
--   and descriptions in admin → Products. Review the HOLD notes first:
--     SELECT p.name, s.review_notes FROM public.product_sourcing s JOIN public.products p ON p.id = s.product_id
--      WHERE s.review_notes ILIKE '%HOLD%' OR s.review_notes ILIKE '%confirm%';
--   Price ranges kept from the stock list:
--     SELECT p.name, v.name, v.price, s.price_note FROM public.variant_sourcing s
--       JOIN public.product_variants v ON v.id = s.variant_id JOIN public.products p ON p.id = v.product_id
--      WHERE s.price_note IS NOT NULL ORDER BY p.sort_order, v.position;
--   Bring a demo product / collection back: admin → Products / Collections → Active, or
--     UPDATE public.products SET is_active = TRUE WHERE slug = '<slug>';
-- ═════════════════════════════════════════════════════════════════════════════
