-- ═════════════════════════════════════════════════════════════════════════════
-- 36_seed_inventory_update.sql — Dock One Solutions
-- GENERATED by scripts/db/inventory/build_update.py from the client's second stock list
-- (Categorized_Product_Stock.xlsx). Do not hand-edit — change the script and re-run it.
--
-- PURPOSE      Applies what the second stock list adds to the catalogue 34 created (34 is live,
--              so this is a separate step). No prices in this list: new items arrive OFF.
--                · NEW product  ASUS VivoBook E1504FA-BQ2909 — 1 in stock, no price (switched off)
--                · NEW variant  JBL Tune 730BT — White, 1 in stock, no price (switched off)
--                · STOCK        the stock list's count wins (approved), written only while the
--                               variant still holds 34's figure (sales since then are respected):
--                               A1504VA-BQ541 1 → 2 · Logitech MK270 2 → 3 · Cruzer Blade 16GB 0 → 1
--                · DETAILS      Blackshadow keyboards: colour Black · Seagate One Touch "2TB Black"
--                               → "2TB" (3 units, 2 stated Black) · tag "gaming laptop" on the
--                               sheet's gaming laptops (TUF A18, LOQ 15AHP9, both Cyborg 15s)
-- DEPENDS ON   34_seed_inventory (refuses to run without it).
-- RULES        rows by slug + variant name; marker 'seed_36_inventory_update'; self-verifying.
-- SAFE TO RE-RUN: yes (second run is a no-op).
-- ═════════════════════════════════════════════════════════════════════════════

DO $seed$
DECLARE
  c_marker CONSTANT TEXT := 'seed_36_inventory_update';
  c_note   CONSTANT TEXT := 'From the second stock list (Categorized_Product_Stock.xlsx)';
  r        RECORD;
  v_n      INT;
BEGIN
  IF EXISTS (SELECT 1 FROM public.app_config WHERE name = c_marker) THEN
    RAISE NOTICE '36_seed_inventory_update: already applied (app_config %) — skipped', c_marker;
    RETURN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.app_config WHERE name = 'seed_34_inventory') THEN
    RAISE EXCEPTION '36_seed_inventory_update: run 34_seed_inventory.sql first';
  END IF;

  -- ── 1. New product: ASUS VivoBook E1504FA-BQ2909 (no price → its variant starts OFF) ───────
  INSERT INTO public.products (slug, brand, name, category_id, tags, sort_order)
  VALUES ('asus-vivobook-e1504fa-bq2909', 'ASUS', 'ASUS VivoBook E1504FA-BQ2909', 'laptops', ARRAY['laptops']::TEXT[], 135)
  ON CONFLICT (slug) DO NOTHING;

  INSERT INTO public.product_variants (product_id, name, price, position, is_active)
  SELECT p.id, 'Standard', 0, 0, FALSE FROM public.products p WHERE p.slug = 'asus-vivobook-e1504fa-bq2909'
  ON CONFLICT DO NOTHING;

  INSERT INTO public.product_sourcing (product_id, official_title, official_url, wording_type, review_notes)
  SELECT p.id, 'E1504FA', 'https://www.asus.com/us/supportonly/e1504fa/helpdesk_service_guide/', 'Official title / model label only',
         'Manufacturer model support; BQ2909 configuration not confirmed. Not in the first workbook''s stock rows and no price supplied: set a price, then switch the variant on.'
    FROM public.products p WHERE p.slug = 'asus-vivobook-e1504fa-bq2909'
  ON CONFLICT (product_id) DO NOTHING;

  -- ── 2. New variant: JBL Tune 730BT — White (no price → OFF) ────────────────────────────────
  INSERT INTO public.product_variants (product_id, name, option_values, price, position, is_active)
  SELECT p.id, 'White', '{"Colour":"White"}'::jsonb, 0, 1, FALSE FROM public.products p WHERE p.slug = 'jbl-tune-730bt'
  ON CONFLICT DO NOTHING;

  -- stock + sourcing for both new variants
  INSERT INTO public.inventory (variant_id, product_id, stock_level)
  SELECT v.id, v.product_id, d.qty
    FROM (VALUES ('asus-vivobook-e1504fa-bq2909', 'Standard', 1), ('jbl-tune-730bt', 'White', 1)) AS d(slug, name, qty)
    JOIN public.products p ON p.slug = d.slug
    JOIN public.product_variants v ON v.product_id = p.id AND lower(v.name) = lower(d.name)
  ON CONFLICT (variant_id) DO NOTHING;

  INSERT INTO public.variant_sourcing (variant_id, source_category, source_description, colour, price_note)
  SELECT v.id, d.category, d.description, d.colour,
         'No selling price in either stock list — variant switched off until a price is set. ' || c_note || ', row ' || d.row || '.'
    FROM (VALUES
      ('asus-vivobook-e1504fa-bq2909', 'Standard', 'Laptop', 'ASUS VIVOBOOK E1504FA-BQ2909', NULL, 22),
      ('jbl-tune-730bt', 'White', 'Headphones', 'JBL OVER HEADPHONE T730 BT - WHITE', 'White', 9)
    ) AS d(slug, name, category, description, colour, row)
    JOIN public.products p ON p.slug = d.slug
    JOIN public.product_variants v ON v.product_id = p.id AND lower(v.name) = lower(d.name)
  ON CONFLICT (variant_id) DO NOTHING;

  -- ── 3. Stock corrections: only where the stock still holds 34's figure ─────────────────────
  FOR r IN
    SELECT v.id AS variant_id, d.slug, d.name, d.qty, d.old, d.row, i.stock_level
      FROM (VALUES
      ('asus-vivobook-a1504va-bq541', 'Standard', 2, 1, 21),
      ('logitech-mk270-wireless-keyboard-mouse-combo', 'Standard', 3, 2, 37),
      ('sandisk-cruzer-blade-cz50', '16GB', 1, 0, 83)
      ) AS d(slug, name, qty, old, row)
      JOIN public.products p ON p.slug = d.slug
      JOIN public.product_variants v ON v.product_id = p.id AND lower(v.name) = lower(d.name)
      JOIN public.inventory i ON i.variant_id = v.id
  LOOP
    IF r.stock_level = r.old THEN
      UPDATE public.inventory SET stock_level = r.qty WHERE variant_id = r.variant_id;
      UPDATE public.variant_sourcing
         SET price_note = concat_ws(' ', price_note,
               format('Stock set to %s from the second stock list (row %s); the first workbook said %s.', r.qty, r.row, r.old))
       WHERE variant_id = r.variant_id;
    ELSE
      RAISE NOTICE '36_seed_inventory_update: % / % stock is % (not 34''s %) — left alone; the stock list says %',
        r.slug, r.name, r.stock_level, r.old, r.qty;
    END IF;
  END LOOP;

  -- ── 4. Details ─────────────────────────────────────────────────────────────────────────────
  UPDATE public.variant_sourcing s SET colour = 'Black'
    FROM public.product_variants v JOIN public.products p ON p.id = v.product_id
   WHERE s.variant_id = v.id AND p.slug = 'blackshadow-keyboard' AND s.colour = 'Not specified';

  UPDATE public.product_variants v SET name = '2TB'
    FROM public.products p
   WHERE p.id = v.product_id AND p.slug = 'seagate-one-touch-portable-hdd' AND v.name = '2TB Black';
  UPDATE public.variant_sourcing s
     SET colour = 'Black (2 of 3 units); 1 not specified',
         price_note = concat_ws(' ', price_note, 'The second stock list splits the 3 units: 1 "2TB" (row 70) + 2 "2TB Black" (row 71).')
    FROM public.product_variants v JOIN public.products p ON p.id = v.product_id
   WHERE s.variant_id = v.id AND p.slug = 'seagate-one-touch-portable-hdd' AND v.name = '2TB';

  UPDATE public.products SET tags = array_append(tags, 'gaming laptop')
   WHERE slug IN ('asus-tuf-a18-fa808uh-rs74', 'lenovo-loq-15ahp9', 'msi-cyborg-15-core-7-240h', 'msi-cyborg-15-i5-13420h')
     AND NOT ('gaming laptop' = ANY (tags));

  INSERT INTO public.app_config (name, value) VALUES (c_marker, to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SSOF'))
  ON CONFLICT (name) DO NOTHING;

  -- ── 5. Self-verification ───────────────────────────────────────────────────────────────────
  SELECT count(*) INTO v_n
    FROM public.product_variants v JOIN public.products p ON p.id = v.product_id
    JOIN public.inventory i ON i.variant_id = v.id
   WHERE NOT v.is_active AND v.price = 0
     AND ((p.slug = 'asus-vivobook-e1504fa-bq2909' AND v.name = 'Standard' AND i.stock_level = 1)
       OR (p.slug = 'jbl-tune-730bt' AND v.name = 'White' AND i.stock_level = 1));
  IF v_n <> 2 THEN RAISE EXCEPTION '36_seed_inventory_update: expected the 2 new (switched-off) variants, found %', v_n; END IF;

  SELECT count(*) INTO v_n FROM public.products
   WHERE 'gaming laptop' = ANY (tags) AND slug IN ('asus-tuf-a18-fa808uh-rs74', 'lenovo-loq-15ahp9', 'msi-cyborg-15-core-7-240h', 'msi-cyborg-15-i5-13420h');
  IF v_n <> 4 THEN RAISE EXCEPTION '36_seed_inventory_update: expected 4 gaming-laptop tags, found %', v_n; END IF;

  RAISE NOTICE '36_seed_inventory_update: +1 product, +1 variant (2 units, both awaiting a price), 3 stock corrections, details';
END $seed$;

-- ═════════════════════════════════════════════════════════════════════════════
-- OPS NOTE — 36_seed_inventory_update
--   Price the two new items in admin → Products, then switch their variant on:
--     ASUS VivoBook E1504FA-BQ2909 (whole product stays hidden until then) and JBL Tune 730BT — White.
--   A stock correction that was skipped (because the item sold since 34) is reported as a NOTICE.
-- ═════════════════════════════════════════════════════════════════════════════
